// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedData.Context;

#nullable disable

namespace SeedData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806144003_BogusSeedDataVi")]
    partial class BogusSeedDataVi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SeedData.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fa56dc2-a1ba-4357-a988-2936b1b09a40"),
                            MoTa = "Thương biển tím đâu tôi ghế nghỉ lầu thì ruộng ghế đồng áo quần kim thuyền hết lỗi biết mượn thế hai là thuê biển anh đã là độc anh em chìm em sáu đạp áo gió ba tui dép mướn bè tô năm quê vẽ chết bảy năm tô.",
                            TenSanPham = "Practical Concrete Keyboard"
                        },
                        new
                        {
                            Id = new Guid("d92e57be-91f7-4ba2-a7e7-7482ce316afc"),
                            MoTa = "Xuồng vàng tô là nón xuồng độc quần ghét chìm tui lỗi cái tủ tàu thích kim tím ừ xuồng gió không vẽ bảy khoan bàn hai núi xuồng chết xanh tím đỏ độc giết ờ á gió kim việc làm núi tám mướn đỏ chìm may đồng mây vàng.",
                            TenSanPham = "Gorgeous Soft Pants"
                        },
                        new
                        {
                            Id = new Guid("8d1264f7-c6ea-454b-bace-afcc0ab1e4c0"),
                            MoTa = "Á nước đá thôi trăng chìm kim ừ hết chín thôi leo nước bảy quần lỗi được anh giết ừ hết thôi chết thế nón tui quê mượn việc tui ừ phá trời con thích áo hàng tàu là hai không bạn lầu đồng con đồng năm tàu vàng thuê.",
                            TenSanPham = "Tasty Metal Shirt"
                        },
                        new
                        {
                            Id = new Guid("427598ce-38ea-43a0-bd1c-5e3aa4f8161b"),
                            MoTa = "Làm cửa khâu mười đập quê đồng xanh là vẽ máy nón bè tàu ba đỏ cái á việc sáu trời đá năm yêu nhà mua nước hương năm con ghét xe leo việc leo khoan con ngọt em năm lỗi làm chìm mười nha nhà xanh chết khoảng cái.",
                            TenSanPham = "Handcrafted Metal Salad"
                        },
                        new
                        {
                            Id = new Guid("c87b7558-51fe-4349-8189-7cf2947123d5"),
                            MoTa = "Máy đang đánh đập ác chết đồng đá xanh một dép năm anh trời hết đánh thương nghỉ bàn em quê bè mướn hương hàng tô may trời nghỉ xe xuồng đang biển vàng gió mướn quần chín ba anh đập bảy quê gì mướn viết mượn thích tủ bè.",
                            TenSanPham = "Gorgeous Plastic Gloves"
                        },
                        new
                        {
                            Id = new Guid("2033fdb3-63c6-4c8d-a858-2a7026080c8f"),
                            MoTa = "Sáu thôi nha nón đã được tím xanh phá đồng nhà nghỉ tui đã yêu thế em đâu bè con giày cái gì lầu làm đâu hết em giết cái nước khoảng cái hương sáu giết bàn bạn nha đồng đánh khoan tui bơi đang việc gì anh ghế thương.",
                            TenSanPham = "Unbranded Steel Chicken"
                        },
                        new
                        {
                            Id = new Guid("863a14b8-85e6-4e57-b869-19495bedd04a"),
                            MoTa = "Thế leo đang dép cái khoan hàng áo năm xuồng viết đánh nhà gió vá khoan trời ờ tủ cái bàn thích tám đâu yêu đã dép đập cửa bảy lỗi biết đập đang thuyền độc nước hết hết mượn thì leo vá đang nghỉ ruộng ngọt ác trăng đánh.",
                            TenSanPham = "Small Rubber Salad"
                        },
                        new
                        {
                            Id = new Guid("ea004267-3ff3-49a2-a1bd-9d4bb3252ab1"),
                            MoTa = "Nón yêu thuyền đạp ác xe ghét đang thì hết nước hết đỏ núi xanh thì hết phá hàng thì chín tím nghỉ mướn quê ngọt xe ừ đạp ghế hóa bơi áo tím chỉ thôi ruộng bè anh không đâu vá mười không bảy leo là tủ áo ừ.",
                            TenSanPham = "Practical Steel Tuna"
                        },
                        new
                        {
                            Id = new Guid("b25cd3c6-5705-41b7-ae3d-5940379bb4d6"),
                            MoTa = "Đã thuê ừ hương á mướn bàn làm ờ lầu một xuồng em bạn biển may nhà cửa chết đạp ừ vá áo cửa tím năm biển thì lầu nhà kim hai mướn mướn chìm đá gió đá cái kim chỉ ghế biết khoan anh mười bơi bơi ngọt chín.",
                            TenSanPham = "Fantastic Granite Mouse"
                        },
                        new
                        {
                            Id = new Guid("faa30656-daa6-4cad-a42d-9460d87cf6b5"),
                            MoTa = "Em ừ cái biển năm hương thuyền vẽ ngọt đánh xanh cửa ác làm hết chết máy thế một tám mướn xuồng tàu quê đang con hết mây đã cửa viết cửa trời thuê gì giày chỉ ngọt thế hai hương không tôi bảy ba vẽ tám cửa phá chết.",
                            TenSanPham = "Intelligent Rubber Salad"
                        },
                        new
                        {
                            Id = new Guid("f5a9d875-e5fc-4096-a33c-39322f149925"),
                            MoTa = "Lỗi gì khoan đá sáu ừ leo tàu làm chết cái vẽ bàn tôi mướn ghế áo quần đâu hai quần một đâu bàn được bè anh đang lỗi xanh hết độc thuyền hết phá mua bạn tím tàu giày may hết chỉ việc cửa hết cửa mua mua thuyền.",
                            TenSanPham = "Fantastic Metal Sausages"
                        },
                        new
                        {
                            Id = new Guid("35596bc4-938c-45fc-9791-a9563807e6e2"),
                            MoTa = "Núi năm yêu bạn nón thương đâu ác nghỉ yêu ghét lỗi núi không núi máy nước ờ viết phá đạp thuyền hết chỉ em xuồng viết làm yêu ác á biết làm đã phá đồng máy quần vá mười đỏ thì dép tàu áo mướn chìm việc ghế yêu.",
                            TenSanPham = "Gorgeous Fresh Computer"
                        },
                        new
                        {
                            Id = new Guid("8a5e51ad-a05e-4c9a-8486-e6d51fcca987"),
                            MoTa = "Giết đang chín thuyền quần khâu đâu dép may kim quần nha áo thương lầu thương thuyền mua núi tô con ừ cửa giày khoan leo anh thế thì máy cửa vàng khoảng kim đã thế tím hóa tôi mua trời chìm năm mây khoan dép hàng em biển một.",
                            TenSanPham = "Intelligent Fresh Ball"
                        },
                        new
                        {
                            Id = new Guid("96446d88-6de4-4e68-ba44-00ab99e41039"),
                            MoTa = "Chìm khoan tôi mướn đâu vẽ núi ba khoảng năm nha đâu mười hết phá ừ lỗi biết tàu đỏ việc hai thích hàng viết hết ba xanh kim mướn lầu biển tám thôi khoảng quê tui mua hương bảy nha đã là không tàu núi mướn vàng khâu tàu.",
                            TenSanPham = "Refined Metal Sausages"
                        },
                        new
                        {
                            Id = new Guid("8f10e18a-5736-47c4-ba05-898b50fb1a7c"),
                            MoTa = "Thương thuê khâu hóa gió ghét ba thương việc em nha ruộng mượn nón á sáu em thế làm tám thương con năm ừ hàng mười ruộng nha sáu khoan khoan thương hai tàu ngọt biển thích tàu núi thì đỏ nón tui tôi đã lầu tím khoan chín lầu.",
                            TenSanPham = "Rustic Metal Car"
                        },
                        new
                        {
                            Id = new Guid("7e100bbb-b597-4bf9-ae0b-7e7434d374b9"),
                            MoTa = "Tui bạn xe thuyền bốn mua mười bè áo đá dép đâu nghỉ áo thích gió một lỗi ruộng thôi đánh hết bốn bàn dép ờ tôi ừ là không thôi nhà cái nghỉ bốn đồng đồng ghét leo khoảng thôi đâu khoảng kim được hàng vàng chết á thích.",
                            TenSanPham = "Ergonomic Concrete Hat"
                        },
                        new
                        {
                            Id = new Guid("d16f97c3-88e4-492c-b814-e5915b4e9c21"),
                            MoTa = "Ruộng quê bảy ngọt ghét đồng lỗi ác mây chìm em đâu biển đã bè khâu áo đánh khâu đá vá mây việc vá bạn con ruộng mua bàn núi mua biển khâu thế chín là năm gió làm năm nha đâu giày nước hết bảy thế thuyền thuyền tàu.",
                            TenSanPham = "Fantastic Cotton Chicken"
                        },
                        new
                        {
                            Id = new Guid("a27e8016-15db-4a13-9c3e-6bb972466bd7"),
                            MoTa = "Ác quê thương đã vá tủ ghét viết giày chỉ tím hóa đâu thuê biết yêu được biển được hàng áo thương tím ruộng đập dép năm lầu em một đánh vá dép khâu tàu hết việc hai làm chìm ngọt á yêu quê biết thôi xanh trời mây đá.",
                            TenSanPham = "Awesome Soft Computer"
                        },
                        new
                        {
                            Id = new Guid("df314762-fcc0-46d3-8105-3599a42f0e29"),
                            MoTa = "Giày bè ba đánh em hai nước đang kim đồng khoảng mướn đâu chín anh bạn khoan đỏ bạn thuyền nhà cửa tím hết hóa yêu khâu thích chìm biết biết tám thế anh ghế biển bảy sáu gió đập mua bàn được đỏ bè nhà hết bảy thuyền anh.",
                            TenSanPham = "Rustic Wooden Soap"
                        },
                        new
                        {
                            Id = new Guid("97935b7e-16af-4663-b3e7-162455b623eb"),
                            MoTa = "Khoan nước tàu chín việc ba nghỉ đang hai không đang nón nón ghế nhà việc ngọt kim mướn xuồng tàu làm khâu lầu làm việc nhà mua xuồng nghỉ đã năm tủ ờ cửa nón ruộng thích hóa đâu xe hàng ngọt chỉ leo bạn hết khoảng nha chỉ.",
                            TenSanPham = "Rustic Frozen Chicken"
                        },
                        new
                        {
                            Id = new Guid("cd97b4b4-335e-42e6-8d2a-432a97472219"),
                            MoTa = "Nước gió mượn độc kim đang nghỉ được viết đỏ vẽ chết trời máy mướn may hóa được nhà thích một biển hai bàn tàu mây năm làm đập lỗi ngọt tôi thương biển trăng đồng phá thôi lỗi bạn thuê viết tô con là ừ nghỉ núi thuê quê.",
                            TenSanPham = "Incredible Steel Pants"
                        },
                        new
                        {
                            Id = new Guid("c805d2b5-a1c5-42fc-af33-bf6bcc970679"),
                            MoTa = "Đồng chìm tím hai á dép đâu dép áo biết khoan tủ cửa là bàn ba đập hết thì thuyền áo nhà gì xuồng vẽ đâu giày khoảng gió nghỉ không núi nước nước khoan nước thuyền ghế khâu đạp ghế đạp khâu chết lỗi tám thuê biết nón dép.",
                            TenSanPham = "Small Fresh Pants"
                        },
                        new
                        {
                            Id = new Guid("a0cb5455-329b-44ec-b2f6-bd024f499846"),
                            MoTa = "Ác thương ba đồng thích giết xe biển ác bàn ngọt xe lầu ngọt đỏ đánh đá ngọt ghế núi tô bơi đang mượn gì giày ác ác bốn bàn yêu á tím đang tôi mười hết trời bốn hương cửa kim mướn đỏ thì nha gió gì thế giày.",
                            TenSanPham = "Practical Steel Chair"
                        },
                        new
                        {
                            Id = new Guid("9b081927-aa9c-4846-977a-6326143911e1"),
                            MoTa = "Trời thuyền chín làm chín bốn giết làm vá một con đã đánh may thương nước nghỉ con vá em núi chỉ nhà cửa ghét bàn giết phá chỉ nhà ghét mượn đạp đỏ đánh cửa cái trời chết lỗi thuê kim đỏ ghế ừ nha phá ác năm tôi.",
                            TenSanPham = "Handcrafted Steel Sausages"
                        },
                        new
                        {
                            Id = new Guid("9b87c32f-50e8-420c-b9fa-deeb126357e8"),
                            MoTa = "Bè ác được thuê ừ mượn xanh anh kim tủ yêu hai cửa quần chết mướn lỗi xe một tôi anh thế bàn vẽ áo xanh ờ á khoan nhà khoan chết dép không ác độc bơi đâu chết ngọt mua bảy dép ừ tui đạp nón đang biết mướn.",
                            TenSanPham = "Small Rubber Cheese"
                        },
                        new
                        {
                            Id = new Guid("6b7e167b-2ca0-4dec-8a2b-6cfa04d9998c"),
                            MoTa = "Hàng vẽ vẽ năm mướn tôi không giày gì kim lỗi hóa cửa leo bàn ghét khâu kim chỉ tô hàng là hóa đánh quê bàn không trăng máy thích xanh vá xe thương hai được giết em khâu thôi khoan quê nghỉ không mượn trăng chết xanh núi vẽ.",
                            TenSanPham = "Handmade Metal Computer"
                        },
                        new
                        {
                            Id = new Guid("1142eed5-f278-42f0-bfe3-cd11d9182b4b"),
                            MoTa = "Nước là xe chìm chín vá tím cái nhà đập chết xuồng hóa bốn biển đã đỏ máy mướn thích bè hết mượn mướn quê đỏ bàn máy giết năm bảy á quần tôi tui tủ ba bơi leo anh tô trăng xe bảy ờ con là nghỉ quê chỉ.",
                            TenSanPham = "Awesome Rubber Computer"
                        },
                        new
                        {
                            Id = new Guid("ae337358-e120-48dd-98fa-7d43b5dcecf8"),
                            MoTa = "Thích nước bàn thuyền bơi biết chết hóa biển tôi ác dép bè giày giết ừ chết lỗi thì máy tui hàng tím đỏ bạn độc thì đánh hết một á nha tui việc thuyền thương mười chín đập lỗi áo dép nước không xe trời thế nghỉ cái một.",
                            TenSanPham = "Fantastic Steel Bike"
                        },
                        new
                        {
                            Id = new Guid("12fe6626-c8ba-4d17-ad20-c88a4369f748"),
                            MoTa = "Tàu biển đâu nhà con máy ba bốn chết chỉ gì bơi chỉ hết mua xuồng núi leo việc mượn tui ác xanh thôi mua vá bạn ba bảy thích bè biết xanh mười hai được mười hàng thuyền ờ được thế độc chín đã ngọt thương độc đã núi.",
                            TenSanPham = "Rustic Steel Shoes"
                        },
                        new
                        {
                            Id = new Guid("109a5309-55ee-4d46-b010-429d6b468a44"),
                            MoTa = "Thì tui hóa gió quê nha đỏ nhà làm giày con tàu ruộng núi cửa biển lỗi là thương em áo xanh tôi nha thế viết mượn áo đá bảy khoan khoảng hương ác nước thuyền cửa việc nước em cái ghét đập tô hương nón tủ núi tủ ờ.",
                            TenSanPham = "Handmade Frozen Bacon"
                        },
                        new
                        {
                            Id = new Guid("34beccdb-d1ea-44f0-a456-0683666662bb"),
                            MoTa = "Lỗi tủ bàn khâu dép tô bảy mua hóa xanh lỗi bàn khoảng thương biết nhà dép may chết làm con làm bàn gió làm biết ghét nón đã thế chín độc đạp nước mua gió đồng thích thì nón việc may tủ mượn yêu chết dép á á làm.",
                            TenSanPham = "Awesome Metal Pizza"
                        },
                        new
                        {
                            Id = new Guid("83a93f7c-ba2e-4ac6-b59b-ff7e2e7359f2"),
                            MoTa = "Được quần mua yêu việc hai đồng hết thôi chết chỉ thì thì núi chìm mượn giết mướn xanh giày áo con kim thích đỏ xuồng chỉ đạp việc là xuồng máy gì đang nhà cửa may thôi khoan mười vá tím ác viết xe trời chín hàng bơi mua.",
                            TenSanPham = "Unbranded Granite Pants"
                        },
                        new
                        {
                            Id = new Guid("5cc8bcf9-2ccf-4f00-9698-5b8c4f2a599a"),
                            MoTa = "Kim đâu cửa thôi gió ừ tôi giày nhà xuồng đâu giết năm ác bè bốn bạn biết quần trăng bảy kim ghế gì việc anh chín được ngọt biết quê khoảng chín yêu kim bàn tủ khâu thương là hết hóa tô khoan gió nha đánh tám ghế đang.",
                            TenSanPham = "Rustic Soft Chips"
                        },
                        new
                        {
                            Id = new Guid("4ec11c21-693e-423d-b1d6-688eb1061d60"),
                            MoTa = "Ờ bốn quê lầu nón mười giày chỉ con lầu thế ác cửa chết yêu ghế tím mượn biển một mười xuồng sáu tôi đồng gì ba leo độc nước chết hương bốn mướn vá vá trăng tôi quê đâu xuồng đá ghế mua tô đá thôi vẽ bàn con.",
                            TenSanPham = "Refined Rubber Hat"
                        },
                        new
                        {
                            Id = new Guid("7107c388-ec31-40b1-a931-27801566db9f"),
                            MoTa = "Hóa núi ba tím ngọt chỉ tui chín áo cái nghỉ tám năm thế ác biết anh thích giết bè ghế bạn ghét xanh làm chín biết kim bảy xuồng nghỉ nước á vẽ ờ hết không hết bàn tôi chết thuê đã chỉ cửa giày ừ xuồng chỉ khoảng.",
                            TenSanPham = "Incredible Steel Shoes"
                        },
                        new
                        {
                            Id = new Guid("43648b97-7991-4b3a-bec0-927696b2aafb"),
                            MoTa = "Bàn đá con chết nhà á mười mượn nón tủ sáu đã ba một thôi đồng một thuyền may viết được mua áo hóa nón khoan đồng khoan anh bè leo viết quần yêu đá bè bè khâu mướn vẽ khoảng chỉ chết quê may bè đồng phá đâu tô.",
                            TenSanPham = "Refined Granite Fish"
                        },
                        new
                        {
                            Id = new Guid("fea76289-a3ac-4ed5-99ce-8f658a667fb6"),
                            MoTa = "Chìm ruộng là á dép máy một gì đỏ bàn vá năm mây yêu đâu ừ khoan ác đâu đã ba á đâu nha nón xanh thế chỉ leo năm tím đỏ thích ghế ghế hai leo vàng đá bè bơi bè tủ hết thế hương xe được đánh đồng.",
                            TenSanPham = "Practical Plastic Hat"
                        },
                        new
                        {
                            Id = new Guid("9f981b13-4956-4974-acac-be5f0706c214"),
                            MoTa = "Cửa vá năm bảy trời dép cửa núi cái tám nghỉ chín khoảng con ba khoảng khâu đâu đá ác khâu đâu lầu em may mây xe khâu xanh thuê đạp thích hương thuê việc khoan nha cái ghét chín vẽ khoan thuê hóa làm trăng bạn đồng chìm quần.",
                            TenSanPham = "Tasty Soft Pizza"
                        },
                        new
                        {
                            Id = new Guid("a2746af9-4c7b-4625-aeba-afc4f9ceff84"),
                            MoTa = "Việc tô ờ cửa một thuê dép may thương quê việc mây quê tôi tô là hương thì tui hương bè đã bạn đang giết bảy tô kim ruộng đồng bè thế viết đang việc ghế chết chỉ khoảng thuyền được quần chín kim nhà bảy biển gì trời nhà.",
                            TenSanPham = "Tasty Steel Ball"
                        },
                        new
                        {
                            Id = new Guid("1e0f3033-162d-41fb-a77c-1408b9a20e61"),
                            MoTa = "Bơi ừ hai máy mua lầu anh mua quần cái gió thuê may hàng hai phá quần hóa khoan nón gió lỗi hóa vàng không xe làm thích bơi cửa mua quê mây giày dép chìm may hết vá trời nước nhà phá hóa bơi viết lỗi thì lỗi bơi.",
                            TenSanPham = "Handcrafted Concrete Pants"
                        },
                        new
                        {
                            Id = new Guid("f159d2e3-0e54-452f-8916-d781c9f45f50"),
                            MoTa = "Tàu cái núi á thuyền đá chỉ chết cái con bơi thích nước xanh gì trăng khoan tôi nghỉ bàn gì biết mua trời vá hết chìm núi gió núi năm núi kim nhà mướn ác vàng em được là một viết đồng thích thuê viết làm khâu phá nước.",
                            TenSanPham = "Small Steel Chicken"
                        },
                        new
                        {
                            Id = new Guid("f577cbd9-8783-4956-9cea-c43dd554dac1"),
                            MoTa = "Tàu may đá chết quê giày leo bàn mười tàu phá được ngọt đạp kim đập tàu viết con hết bơi nón vá đánh kim lỗi tím hàng là mây núi thôi năm ừ nón giày nha thế hương leo độc ờ bạn bè sáu đá xe được thuê đâu.",
                            TenSanPham = "Ergonomic Cotton Computer"
                        },
                        new
                        {
                            Id = new Guid("9ce40971-eb7f-4b45-bcef-d62fbd38268f"),
                            MoTa = "Giết bè năm đồng bè giày tui ba mướn đập bàn được biết biển ờ trời kim được may vàng gió anh dép đỏ đạp may ba hai đá đâu ghế nghỉ hết biết á yêu máy mướn thuyền em bè hết mây quần gió đỏ lầu trời bè tím.",
                            TenSanPham = "Awesome Soft Table"
                        },
                        new
                        {
                            Id = new Guid("246324f5-77b7-453f-ae86-590a27ce73e6"),
                            MoTa = "Dép bàn vàng một thế mướn tím thì hai ác thế cửa đánh nghỉ làm xe vẽ vẽ được một năm nghỉ em quê đâu hóa cái mua bè ác bạn ghét tủ thế ghế em đã tàu ừ hóa hai tủ núi sáu tím đập ừ gì khâu không.",
                            TenSanPham = "Refined Wooden Chips"
                        },
                        new
                        {
                            Id = new Guid("64e2e0c2-e7d1-4866-a8b1-a04406323576"),
                            MoTa = "Bơi em xe thì đánh lỗi bạn giết đã gió con ruộng khoảng bơi vẽ vẽ tôi nón thuê dép xanh yêu mây mười nhà trăng một mây biển quần đâu khoảng tôi cửa tím ừ bạn mười con ghét trời đá gì ác nhà làm năm con đá không.",
                            TenSanPham = "Gorgeous Plastic Sausages"
                        },
                        new
                        {
                            Id = new Guid("15b9ee53-1ae5-489a-b8b2-74a140b7e6ab"),
                            MoTa = "Hai tui bơi biết đã bảy leo đỏ thì mua đỏ đã năm giày bốn ghét yêu hàng tôi vàng tô khâu hương nghỉ em ờ thuyền là được đâu biết năm yêu bảy lầu bơi quần giết ngọt nghỉ nha hết thì mượn leo leo ghế khoan nước hương.",
                            TenSanPham = "Handmade Wooden Salad"
                        },
                        new
                        {
                            Id = new Guid("150c5521-7209-4db6-9193-41314b86ff08"),
                            MoTa = "Dép viết sáu đạp chìm đập chìm ghét ghế vẽ tô nhà ghế đánh ruộng việc biển hết mây bốn hai sáu bơi hai chỉ kim làm chỉ không năm gì chín mười trời ba chết ngọt trăng ừ ba tàu chết xuồng đang tám thuyền giết độc tím khoan.",
                            TenSanPham = "Refined Steel Ball"
                        },
                        new
                        {
                            Id = new Guid("e2e8e963-9cf3-44c6-9a53-913b64aae98d"),
                            MoTa = "Dép khoan độc ghét được đang nghỉ khoan ngọt làm bảy yêu áo con cửa đã không bảy mua đâu quần bè xe ờ bơi ác bơi không vàng năm ghét chỉ ghét leo ừ nón ghét vàng lỗi xe tui đánh hương thích nghỉ tím sáu đang chìm thích.",
                            TenSanPham = "Fantastic Frozen Shirt"
                        },
                        new
                        {
                            Id = new Guid("4a3f300c-c749-40a8-9181-4798c8cf21e2"),
                            MoTa = "Viết ờ chết lầu không nha là đập tám việc khoan thì á thuyền không việc chỉ ác tàu thế tui thích bốn tô quần đánh biết năm thuyền tủ tám núi nghỉ tàu quê ghét hết tui ghét đâu ngọt đỏ kim hết kim cửa lỗi không tàu giết.",
                            TenSanPham = "Gorgeous Fresh Pizza"
                        },
                        new
                        {
                            Id = new Guid("714055c7-5920-45df-9fec-1f60a48cbbf2"),
                            MoTa = "Đập đạp kim biển ờ lỗi con nhà cái may ruộng cái bảy bảy hàng mướn kim mướn bè tô xe không máy ba nón lỗi em anh ghét mướn cửa đồng yêu thích thích tím được trời làm hết là thôi thôi tui á ừ trăng xanh á đỏ.",
                            TenSanPham = "Intelligent Rubber Chair"
                        },
                        new
                        {
                            Id = new Guid("0e444496-f0c9-49a1-bc16-8076d8047016"),
                            MoTa = "Ừ cửa quê ba hương chỉ hương thì đập gió nhà chín mây may thương một khoan khoảng lầu năm đập được bè bốn yêu giết giày đạp chìm độc là ghế khoan xanh bơi yêu đập nghỉ khoan kim ác leo việc cái mượn đỏ đập hàng ghét dép.",
                            TenSanPham = "Fantastic Cotton Bacon"
                        },
                        new
                        {
                            Id = new Guid("73fbbd3d-1929-4e62-8f03-b0c3a4cb2a08"),
                            MoTa = "Nước bàn trăng bè cửa may trăng tôi chết xanh độc vá tui không cái một vá nhà biển tôi thôi biết phá tím bàn máy gì nón thế ghế trăng khoảng ghét bè đồng trời cửa ruộng đâu ngọt đã năm tủ anh tủ chết kim biết khoan tui.",
                            TenSanPham = "Small Granite Ball"
                        },
                        new
                        {
                            Id = new Guid("8432cddd-7a74-4d84-bb9f-442d9d2c91c0"),
                            MoTa = "Đồng nón thuyền bạn chín chín bốn tím chỉ á trời phá khoảng lỗi giày thích gió hàng mây bơi bạn biết bạn tím lầu đạp chìm nha vàng thôi hết bốn nghỉ núi hết cửa đồng hết chìm bảy xanh đánh ác xanh máy được vá á thích đạp.",
                            TenSanPham = "Awesome Concrete Bike"
                        },
                        new
                        {
                            Id = new Guid("9c085d41-362e-4661-bf3f-6c947f76ee18"),
                            MoTa = "Bốn đạp thuê đang xuồng ghế xuồng thích khoảng ờ việc hai lầu thuê tui hóa hai ngọt máy tám thế cái ghế hương nước đạp là hương biển mua vàng may đỏ đồng tím tui đâu anh á bàn mượn được nước vàng đỏ thì làm may bạn lầu.",
                            TenSanPham = "Intelligent Cotton Sausages"
                        },
                        new
                        {
                            Id = new Guid("ede08ec2-391f-4da2-804b-cce6587fa155"),
                            MoTa = "Đá đánh ờ đỏ con bạn tủ tôi đồng á tô xe trăng máy bè chìm đã chìm tàu nghỉ nghỉ trăng trăng chín hai á bốn làm xanh ba ác đánh vàng đã tủ năm thuê con ngọt ác tô nón phá ba xuồng không biết độc ờ ghế.",
                            TenSanPham = "Small Granite Chips"
                        },
                        new
                        {
                            Id = new Guid("fd155938-3c7f-4ca5-a9cf-59f42f9a9b35"),
                            MoTa = "Tô tui thương ừ em nha thương biết giết bảy khoan đạp một gió hai nha thế đánh tủ vá ba đỏ hàng xe lỗi lỗi trời đập trời chìm ba thế tàu phá nha một năm áo tô nha vàng bảy ác tím vá sáu hương ừ bảy vẽ.",
                            TenSanPham = "Sleek Metal Gloves"
                        },
                        new
                        {
                            Id = new Guid("dd205dae-4b00-44e6-a363-6fc0c98e15ec"),
                            MoTa = "Tàu thích vá không khoảng giết xanh biển em thuyền lỗi độc nha nón tàu đồng mướn chín bạn tủ khoảng leo con chín việc ruộng tôi độc ghế kim khoan ừ đánh bè là khoan thuyền xanh kim ác nón thì bơi viết vàng quần xanh ghét đập thương.",
                            TenSanPham = "Unbranded Cotton Soap"
                        },
                        new
                        {
                            Id = new Guid("7d46fcd3-d8db-4232-854f-bffa4d0c074e"),
                            MoTa = "Tôi hàng vàng bè em ờ gió chết nha cái bè tím biết làm nhà con sáu không tám xuồng đập nha núi độc may hóa lỗi lỗi khâu đập năm hóa vẽ gió dép lỗi việc nón núi ngọt con đá nước việc quê núi bơi đỏ đã vá.",
                            TenSanPham = "Handmade Cotton Hat"
                        },
                        new
                        {
                            Id = new Guid("ff7b75a3-6c03-4cb6-806c-6d678f0d3b0e"),
                            MoTa = "Thôi bạn là phá chìm nghỉ máy mượn xe ruộng viết dép thuê hàng đồng hết đập chết cái cái bốn thế chín tím năm quê tô thích lầu xanh tàu nha là anh mua vẽ xuồng lỗi hóa đâu đồng tàu vẽ thích yêu leo tôi may đồng hóa.",
                            TenSanPham = "Tasty Frozen Chips"
                        },
                        new
                        {
                            Id = new Guid("f927d8bd-815c-456a-8d63-fa8b0dc756dc"),
                            MoTa = "Viết ghế em đâu bốn một bàn máy chìm bơi đỏ bơi ừ quần thuyền xe đồng cái bàn bảy tui gió chết ruộng tui đã ghét đang đang vẽ thuê quê hóa hóa ruộng tàu cửa một quần yêu hàng đánh hết thuyền sáu xuồng trời hàng ghế khoảng.",
                            TenSanPham = "Licensed Soft Mouse"
                        },
                        new
                        {
                            Id = new Guid("1b1b88e4-7696-4f51-93f5-e33975b140b7"),
                            MoTa = "Thôi hai mây vá tô leo trời hai viết xe việc ghét em vá một đã ghế không chỉ yêu nhà hương đã xe xuồng thuyền thôi máy biết mười tô cửa thôi cái vẽ mượn đập dép hai tím vá hàng trời không máy cửa ruộng đâu đập đã.",
                            TenSanPham = "Practical Rubber Bacon"
                        },
                        new
                        {
                            Id = new Guid("30f86434-3b81-437d-bad5-a7b97784d1f0"),
                            MoTa = "Áo thích một chỉ vàng trăng đánh gió đạp ngọt thì ừ núi đá ba tím anh tôi mướn xanh áo năm thuê tôi bạn ngọt tui gì dép mười vàng bàn lỗi việc núi làm tám độc độc hàng gió tô thuê đã chín leo bơi em nghỉ được.",
                            TenSanPham = "Generic Fresh Ball"
                        },
                        new
                        {
                            Id = new Guid("b7d08146-7f64-479c-9243-a001071b00ca"),
                            MoTa = "Đồng viết ghét đâu biển dép bốn hóa mười làm sáu khâu ừ trăng nha được hàng thì đánh độc bạn hết phá kim được lỗi thế bè đang tím á á hai bàn phá núi mướn ruộng không khoảng giày nón xanh quần ghét được mượn được khâu gió.",
                            TenSanPham = "Gorgeous Soft Sausages"
                        },
                        new
                        {
                            Id = new Guid("59ab64ba-f470-4a58-8b78-598a8c19756c"),
                            MoTa = "Hóa việc dép chín mây vẽ hàng thôi gió dép ghế được phá bè á nghỉ sáu khoảng tám hết đang hóa con là thương đỏ biết chỉ vàng á thuê mây tím biển em chết một chín con leo anh thương giày ừ năm đá một trời đang nghỉ.",
                            TenSanPham = "Handmade Frozen Car"
                        },
                        new
                        {
                            Id = new Guid("670c2958-ea84-4b1e-b7be-d604bbc439e8"),
                            MoTa = "Ờ thuê gió mướn chín nước leo máy mây con ừ trời mua leo mượn ờ hết nghỉ tôi tàu đá lầu hết sáu là đá nghỉ ác đang tàu hóa đã lỗi khâu không kim á biết vẽ thì đồng đá thuyền lỗi giết đá anh nghỉ núi việc.",
                            TenSanPham = "Ergonomic Plastic Computer"
                        },
                        new
                        {
                            Id = new Guid("17ee2d32-7944-47c3-b8ea-ab4cfb853235"),
                            MoTa = "Chết bè hương bốn mượn yêu bảy khoảng bè ruộng xuồng giày biết may hết vá xuồng ờ biết đỏ xanh chín chỉ thuyền xe tui hóa vá nhà trăng bốn gió bơi xuồng nghỉ núi không là bạn xe thôi thế khoảng làm vàng ba quần kim lỗi leo.",
                            TenSanPham = "Sleek Rubber Mouse"
                        },
                        new
                        {
                            Id = new Guid("8b4852a9-61e3-48ee-a1ac-6ea34b49135e"),
                            MoTa = "Xe may thuê phá giày đập tô giết ác gió đã bè trời thôi mây một leo tám không tím tím leo tám hóa đỏ đạp bốn tui giày nghỉ nhà nón bàn khâu tô đâu thương mười năm anh đồng quê may con thuê gì tui nghỉ sáu ờ.",
                            TenSanPham = "Sleek Cotton Hat"
                        },
                        new
                        {
                            Id = new Guid("882fbf45-1fe6-4921-b635-9d20c6eb29b5"),
                            MoTa = "Đâu quần đánh đâu thì phá mượn đang được ghét giày năm thì máy núi năm bạn giày dép lỗi khâu á đỏ thích khoan năm gió nha chín thì hết khoan xuồng yêu hóa khoảng nước em mượn nước con ba tôi ruộng tô ghét ngọt thương sáu núi.",
                            TenSanPham = "Refined Steel Table"
                        },
                        new
                        {
                            Id = new Guid("c5f307a8-1848-4ada-b8da-9a5f072f1dfa"),
                            MoTa = "Nhà bơi trăng ghét hàng máy ghế ờ ác ừ đang gió mướn chỉ thích con nón xanh giết tô vàng trăng áo biển bơi thuê bàn đã dép xe đang dép trời anh mây bốn trăng thôi không chìm lỗi nghỉ độc đập con đỏ đánh bạn kim tủ.",
                            TenSanPham = "Unbranded Concrete Towels"
                        },
                        new
                        {
                            Id = new Guid("562f5707-030e-49c0-8306-6dc2163772bb"),
                            MoTa = "Ba lầu phá mây mướn á quần tủ cái nón đập gì lỗi nước tô chết áo đá cửa vẽ con ờ cửa không leo ghét ba khoảng khoảng được khoảng tủ á đã tủ ghế tui trăng vàng khoảng mây mây làm đồng khoan hương biết leo núi áo.",
                            TenSanPham = "Small Granite Mouse"
                        },
                        new
                        {
                            Id = new Guid("a0e4d4a1-0c67-4971-b102-e99465d9c449"),
                            MoTa = "Năm quê mua lầu chỉ cửa gió tàu tủ viết mây hết ác quê bốn được được cái mua được quần không chỉ đá đồng hết xe chỉ hóa ác viết tàu phá xanh nón tím leo đá hương bốn thích nước không hết vàng bơi giết đạp tủ bè.",
                            TenSanPham = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = new Guid("2fd1dae4-c138-448c-89c4-887e11ad4797"),
                            MoTa = "Ghét lầu ừ xuồng vàng bốn thì vá hết tủ mướn bàn con chỉ tui con sáu thương không đánh vẽ làm viết hai bốn chết ghế khâu bạn kim biển chết tui đánh á nghỉ sáu việc hương thì ghế bàn gió giết tàu biển bạn việc em nghỉ.",
                            TenSanPham = "Licensed Steel Chips"
                        },
                        new
                        {
                            Id = new Guid("0d5d8b7f-874a-4328-9739-3a9d0aae66dc"),
                            MoTa = "Áo biển đập năm thế đang phá lỗi tím may đã đã em vẽ việc chìm đỏ đã khâu tô kim mua biển vá sáu quê việc ghế là sáu đâu là gió bạn đạp đánh mua sáu một may chìm bảy khoảng độc đồng anh tui đập nước thôi.",
                            TenSanPham = "Practical Soft Table"
                        },
                        new
                        {
                            Id = new Guid("30887411-2e36-4ad7-932d-65da23aa1084"),
                            MoTa = "Quê em khâu viết em việc lầu khâu không mua vẽ con thôi mây thuê giày bè gió đỏ hương biển sáu em em tô đang thì viết tàu con bè hóa mướn đánh khâu vàng tám yêu ờ giết tám gì tô cái đâu khâu khoảng làm tàu đập.",
                            TenSanPham = "Tasty Granite Ball"
                        },
                        new
                        {
                            Id = new Guid("56589ac7-3fd5-4a5d-a362-2d8c1053d5ea"),
                            MoTa = "Khoảng chín thế phá bạn tôi nón thì đánh trời trăng bơi ghế hàng phá bảy hóa núi biết nước trăng anh dép chìm dép bàn việc quê đang đang hóa thì tàu độc gì cửa biết ghế tui em leo ghế mượn cửa gì trời thích khoan gió tím.",
                            TenSanPham = "Sleek Rubber Mouse"
                        },
                        new
                        {
                            Id = new Guid("2fa0b9fa-b393-4243-a4ca-fbb302c3d5dd"),
                            MoTa = "Hai biết ba thì đánh hết đỏ cái hàng thuê mượn khâu leo hàng leo ngọt ừ đâu sáu bốn biển thì phá ờ cửa dép ruộng mướn cái núi nghỉ cái nước tôi lỗi mướn vá vá đồng đạp gì giết trời đâu là không nhà mượn con được.",
                            TenSanPham = "Tasty Cotton Bacon"
                        },
                        new
                        {
                            Id = new Guid("973b83f8-fe08-4646-8d5d-94a4aad51217"),
                            MoTa = "Thôi ghét á bảy thôi con không gì làm khoan viết thích chín bốn nón ngọt bàn nha là thương không ghét làm đâu kim hai năm vẽ xanh mua mây thuyền việc tám không thuê hương hết viết kim đồng mười nước khoan ba tôi nha độc ghế hai.",
                            TenSanPham = "Fantastic Concrete Towels"
                        },
                        new
                        {
                            Id = new Guid("fb208092-a8ad-4f39-87b7-807d271055db"),
                            MoTa = "Ruộng bè yêu nghỉ leo đánh con dép là kim làm chín trời leo khoảng thôi vàng thì hàng biển đỏ con đã được khâu con bốn mây chìm ừ thuyền kim nghỉ bạn bảy nón thuê tủ trăng gì ờ thuyền thương bơi biết bè tui viết hóa vá.",
                            TenSanPham = "Gorgeous Frozen Mouse"
                        },
                        new
                        {
                            Id = new Guid("87cf36df-26b0-4339-93c9-5852a4ea4122"),
                            MoTa = "Em nón ghế lầu ừ nha nhà em nhà trăng viết nước ác thế đã vẽ yêu mua dép leo bơi không đánh nón một tám viết giết kim việc giày đã nghỉ á nón tàu biển đồng gì tủ ruộng trời thương quần quê làm chỉ máy quê thương.",
                            TenSanPham = "Gorgeous Soft Cheese"
                        },
                        new
                        {
                            Id = new Guid("544869c6-a83a-463a-9445-96a3dad02bc7"),
                            MoTa = "Giết viết bàn sáu thuyền nha tui ờ hết bàn chết mua bè đỏ đập gì làm đỏ vàng biết trăng bốn dép vẽ biết ờ á thế bảy tủ gió nhà trời phá nha bốn tám hàng mua đánh đập tô đạp thế được tô thích mười máy tui.",
                            TenSanPham = "Tasty Metal Table"
                        },
                        new
                        {
                            Id = new Guid("bd8bcd0f-266f-4140-9a8e-fec837679d59"),
                            MoTa = "Thế thế xe tàu trời thế ruộng đạp khâu đồng hương vá ruộng không tôi thôi hương cửa bơi á hàng anh anh bạn vá vá nghỉ chìm xuồng khâu ba lầu là xe biển khâu ghét dép xe độc xanh máy tô quê quê trời áo năm tôi một.",
                            TenSanPham = "Ergonomic Cotton Sausages"
                        },
                        new
                        {
                            Id = new Guid("1bab3ab9-6fb1-423c-8d2d-d7c15e80ca05"),
                            MoTa = "Giày máy chết dép mượn ruộng ngọt độc bàn hàng kim thương hết khoảng sáu ghét ghét bảy khâu được chỉ bè anh làm tôi mười viết nhà chết ghế biết nón thế tôi viết xe xanh một gió tui mượn làm ghét ngọt biết á leo năm giết thương.",
                            TenSanPham = "Licensed Concrete Bike"
                        },
                        new
                        {
                            Id = new Guid("2ad41ad8-84ff-4771-9079-325742128122"),
                            MoTa = "Tui không ghét năm hết bốn khâu nước hương chín máy bạn bơi việc cái phá quê bè đã bảy yêu độc bàn cửa chìm xanh đập con trời cửa chỉ hết lầu đồng mua ghế khâu gió đang tám hai đồng anh leo ghế xanh mượn chết thương nón.",
                            TenSanPham = "Sleek Plastic Bike"
                        },
                        new
                        {
                            Id = new Guid("d4291a0a-f76d-4696-9694-1537ac4060a5"),
                            MoTa = "Ghế anh khoan lầu được đâu ngọt ruộng gió ừ cái thế leo là hóa lầu xanh được trăng năm tám bè ác khoan đá thương đang giết vá khoảng khoảng khâu đâu em ghế ba con hương khoan trăng ờ nước vẽ vá thuê giày nước thích nước bốn.",
                            TenSanPham = "Practical Plastic Ball"
                        },
                        new
                        {
                            Id = new Guid("b4ce93d1-6b8f-48f5-b243-f20b91be813d"),
                            MoTa = "Xuồng biển bơi cái đồng ờ khâu bè ghế chỉ mướn ngọt thôi nhà nha thuê cửa hàng ừ giày bàn mượn nghỉ may nhà biển quê đâu thương bàn hương đập lầu nha bơi thì chết khoảng hai bảy ba con thế gió lỗi đã bè được vẽ được.",
                            TenSanPham = "Handmade Steel Table"
                        },
                        new
                        {
                            Id = new Guid("2b4c1e28-5309-4e70-8ae2-ccedd03f3061"),
                            MoTa = "Chín được hóa chìm mười biết núi biển sáu bạn một tám trăng hàng trời mười bè leo đạp bơi ghế đỏ làm mây vá mây mượn chìm máy dép bơi ừ chìm núi ghét yêu xe phá đá giày hàng ghế thế vàng không bạn chỉ đánh làm con.",
                            TenSanPham = "Tasty Wooden Shoes"
                        },
                        new
                        {
                            Id = new Guid("87388297-cf79-4d80-ab75-197e66ad64db"),
                            MoTa = "Yêu hai gió chết cửa viết đỏ biển mười gì đá làm hóa vá thương biển chết biển đạp hết ngọt bốn áo mượn xe xanh đá á leo ruộng lỗi đâu ba bơi gì ghét phá thuê đỏ tô may ờ độc làm sáu chín nước thế ba thế.",
                            TenSanPham = "Fantastic Wooden Sausages"
                        },
                        new
                        {
                            Id = new Guid("5316cf5a-1689-4773-be63-39b6933bdc56"),
                            MoTa = "Một leo ờ kim quần bơi là quần chín thương là mướn tím mướn ba biển quần khâu tôi đã quê á tô leo ác quê năm bơi việc sáu thương gì mướn chìm biển anh gió nhà may gió nha dép nha đá khoan bốn dép mười em ghét.",
                            TenSanPham = "Generic Cotton Soap"
                        },
                        new
                        {
                            Id = new Guid("d5c53363-e2c5-463d-9f9a-cd4bb233aa64"),
                            MoTa = "Nhà ác khoan hết yêu kim cửa thuyền bàn lỗi nha đâu em đã mười cái đạp thuê biển là giết tám bàn con lỗi yêu quần mây áo đã làm may viết nón thì tím thuê nha hương ờ hai nước thích khoan bơi vẽ tô ừ cửa không.",
                            TenSanPham = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = new Guid("71871d02-3879-45c0-b9eb-db6901583a42"),
                            MoTa = "Vá đã khâu đánh bè dép bạn thế yêu tô bảy con cái sáu mây giày ờ ba á á tám ngọt cái anh gió ruộng quần đạp máy em á tủ nghỉ con thích thì tủ xuồng đồng thôi nha anh mượn ác nha chỉ biển thương quê nha.",
                            TenSanPham = "Intelligent Metal Chicken"
                        },
                        new
                        {
                            Id = new Guid("a6c0154c-26c3-4a27-bfe7-ba0c3cb5333f"),
                            MoTa = "Vàng xe anh vá cái khâu việc thì núi yêu đâu đá được máy hương ác bơi lầu thế đá nha đã thuyền gì bàn leo xe gió kim bảy tím xanh trời nón bàn nha đỏ em đâu mười chìm cửa xuồng làm giết nghỉ ghét anh đang ba.",
                            TenSanPham = "Licensed Cotton Computer"
                        },
                        new
                        {
                            Id = new Guid("bcc476a7-d7cb-4e0b-bb19-e907d1a9b255"),
                            MoTa = "Nhà bàn bè ghế không thì hết nón lầu thế ghế hai mười làm xuồng núi ờ được giày vá hương trăng đánh tám em viết bàn hóa nước bàn bốn đã nha áo biết độc nước thương đồng may không nghỉ cái đỏ tô mây biết ghét được đạp.",
                            TenSanPham = "Tasty Granite Table"
                        },
                        new
                        {
                            Id = new Guid("9af17228-5769-4a79-832c-59958160a767"),
                            MoTa = "Đập đỏ phá may con núi bè dép viết trời á nón dép lầu trăng mướn tôi chìm làm ờ lầu mướn ghét hương viết sáu trăng ghế á hết nha á quê bốn đập biết đạp ruộng thì đang trời hết được tủ mua giết đỏ mướn mướn vẽ.",
                            TenSanPham = "Small Wooden Salad"
                        },
                        new
                        {
                            Id = new Guid("01e7e5d5-96fd-47b8-9b41-79621cb5af6e"),
                            MoTa = "Vẽ đồng anh dép hết khoan áo nước leo ác biết hết con chết nghỉ khoảng tím tô ờ nón thương thế việc cái ghế xuồng áo cửa lầu giày tui may vá lỗi thuyền chìm bảy sáu leo mượn xanh may ngọt trời hàng làm tàu chết xe ghế.",
                            TenSanPham = "Practical Rubber Keyboard"
                        },
                        new
                        {
                            Id = new Guid("96a84b76-9759-44a2-a03e-4afa23f4ac10"),
                            MoTa = "Đập biển giết năm bàn lỗi không nhà biết vàng biết giày vàng phá mây mướn xanh thuê ghét nước tô chết dép mướn thì đang áo xuồng thích nghỉ ruộng xuồng viết việc cửa bảy hương tô ngọt đồng không nước nha lầu gì áo thương nha may chết.",
                            TenSanPham = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = new Guid("95505f98-dfac-4ca7-b45e-bd70aeac1d59"),
                            MoTa = "Hóa nón được tô viết thế chín ừ ác lầu nhà may thôi vẽ dép trời ghế tàu nha tàu viết hương quần leo mua độc vá đâu đã bảy gió dép trời quần tôi việc đạp thì máy bè cái đập thương tàu nghỉ chín máy tàu ruộng ác.",
                            TenSanPham = "Handmade Fresh Car"
                        },
                        new
                        {
                            Id = new Guid("b38aa338-a42e-4b87-88ec-3466b7ba2414"),
                            MoTa = "Ác dép khoảng nghỉ núi may ngọt làm mười giết mây viết thì chìm xuồng năm mượn ba đâu ruộng giày ờ lỗi nhà ừ quê nước nón đâu sáu chín ghét thuê đỏ xuồng gì mướn thôi tô trăng giết thôi ba ruộng nha nghỉ vá được nghỉ ngọt.",
                            TenSanPham = "Intelligent Steel Tuna"
                        },
                        new
                        {
                            Id = new Guid("4cfdb900-5e29-4334-b496-b25dec6ebcbe"),
                            MoTa = "Cái em ghế một năm tím ba bàn đỏ dép may mượn tím kim mượn áo leo ruộng quê kim đỏ thuyền kim hóa gì thích tàu hết bạn ờ nón hết khâu trăng hương ghế ghét xanh anh hương sáu mười chết thế hương bạn khâu quê hai ừ.",
                            TenSanPham = "Ergonomic Plastic Shoes"
                        },
                        new
                        {
                            Id = new Guid("0cb103c9-44c8-4f26-9580-4f587c443248"),
                            MoTa = "Chín đỏ chín quần bốn hóa ờ anh ngọt đập đã dép anh lầu hai cửa em bốn đã quần leo vàng áo cửa hàng nha thích tím gì cái quê bảy bè giày á đánh hóa ghế trời nha trời đã đã nhà đồng khoan gió mười nước đang.",
                            TenSanPham = "Practical Soft Chair"
                        },
                        new
                        {
                            Id = new Guid("8e831be0-b525-4c3c-96db-eef76cf61e10"),
                            MoTa = "Làm quần tô nha yêu chìm leo hai vá thuê năm ba leo chết đập thích mượn được hết hai đá thì á núi một chín nón nước lầu bè vẽ giết ngọt chìm tủ hết trời mướn ừ á ngọt hương hương em vá được năm đập ác biết.",
                            TenSanPham = "Ergonomic Rubber Salad"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
