// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedData.Context;

#nullable disable

namespace SeedData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806144854_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DanhMucSanPham", b =>
                {
                    b.Property<Guid>("DanhMucsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DanhMucsId", "SanPhamsId");

                    b.HasIndex("SanPhamsId");

                    b.ToTable("DanhMucSanPham");
                });

            modelBuilder.Entity("DonHangSanPham", b =>
                {
                    b.Property<Guid>("DonHangsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DonHangsId", "SanPhamsId");

                    b.HasIndex("SanPhamsId");

                    b.ToTable("DonHangSanPham");
                });

            modelBuilder.Entity("SeedData.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("SeedData.Models.DonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("SeedData.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("SeedData.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("884e9a8f-2bba-4897-8dc6-ca3d40163591"),
                            GiaBan = 0m,
                            MoTa = "せいしん 妥協する 太る 漂う 上手 以下 ようい 伐採 すんか 母 渦巻き かいぞく フランス語 〜系 総括 まほうつかい 太る 徳川 ちきゅう 同僚 店 形 こくみん かんしん 不思議 ちきゅう こうちょく ぶそう 形 はちのす きょうかい 掛ける うえる ちかく まぎらす しょうじょう 半額 左手 たいさ 抑制 不健康 悲しみ あびる めいし 右利き 閉じる 俵 さくにゅう どうけつ かん.",
                            SoLuongTon = 0,
                            TenSanPham = "Refined Wooden Chair"
                        },
                        new
                        {
                            Id = new Guid("5523a41f-5cc4-4008-8258-d16f38cc2d23"),
                            GiaBan = 0m,
                            MoTa = "母 施行 しえんする こうせい へいがい あらす まつり あっとうする 母 壊す りゅうこうご どうけつ 旧姓 評価 きひん 急騰 電話 むぼう げんめつ いっさくじつ 斬殺 済ます そんざい とりあえず のき 芸者 しょうゆ 検査 魔法 くつじょく 十台 閉める 先週 げいひんかん 旧姓 伝統 伐採 悲しみ とちょう よくげつ みつ じじょでん にる じぶん 泳ぐ ちえん 不可欠 しえんする はなぢ 迷路.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Steel Table"
                        },
                        new
                        {
                            Id = new Guid("e9d16bdb-4a00-44cd-bec8-20557698c0b6"),
                            GiaBan = 0m,
                            MoTa = "地面 黒板 たつ にんい 陳列室 軒 いう にんい ほんらい きょうふ 廃墟 はんそう かんどうする つなひき 奉仕 靖国神社 ふそく 約する ぼきん たて あらす かわかす こうつう ころす かぜ 零す 掛ける かんそく おどろく ことばつき 底 九日 撃つ いじん さくにゅう たくす 開閉 貫く 絹糸 右利き 推奨 きげんご きゅうりょう こうつう 〜系 ことばつき 漠然 傑作 壊す 日欧.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Concrete Computer"
                        },
                        new
                        {
                            Id = new Guid("7f814ea1-9aed-4d26-b55c-90666f82309d"),
                            GiaBan = 0m,
                            MoTa = "疾走 渦巻き 縛る 俵 そんざい 華やか 手作り 大尉 上手 あっとうする 壊す 徳川 かぜ 無駄 没落 仕方がない こうせい 洋服 漂う 面 始まる うえる 退く 誓い しょうゆ きいろ 投資 みなもと じぶん 施行 果樹 靖国神社 きょうかい 独裁 徳川 窒息 きょうどう 禍根 しばふ 戦没 江戸 あっとうする 新婚旅行 ごふく じきしょうそう 漂う かんしん とりあえず 寮生 泳ぐ.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Frozen Pants"
                        },
                        new
                        {
                            Id = new Guid("99f20d0d-a0df-46b5-925b-e0b98dd21026"),
                            GiaBan = 0m,
                            MoTa = "鍋 復旧 はなはだ りゅうこうご ころす あらあらしい 軒 始まる 全日本 春休み 泳ぐ 米兵 歯を磨く 以下 書き方 しゃっか 魅力 廃墟 こうせい ちがい はちのす うえる 斬殺 よわよわしい たくす 地面 店舗 入江 既に げいひんかん きょうしつ あらあらしい 乗せる つばさ 大丈夫 あらあらしい 軒 金 閉める 果てる いく まつ せっぷく ほうしゅう とふ 誓い 米国 せんりゅう 暇 浮世絵.",
                            SoLuongTon = 0,
                            TenSanPham = "Unbranded Frozen Mouse"
                        },
                        new
                        {
                            Id = new Guid("4503b4ad-0c3d-44f6-8c94-20112538b85d"),
                            GiaBan = 0m,
                            MoTa = "みさき 地面 総括 じぎする うえる こわす 閉じる がいよう 提案する 斬殺 ほうげん かくじっけん じぶん 泳ぐ まもる そんざい おかね 無駄 面 大尉 こいぬ しえんする まほうつかい 先ず 先ず むく ことばつき しょうゆ 窓 おかね 入江 ひきざん たらす 出かける 活用 迷路 済ます 交錯 薬 ないしょばなし 号 狂う じょうじゅん ちきゅう 超〜 宜しく かんりょうてき ひかくする 話 たまご.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Cotton Gloves"
                        },
                        new
                        {
                            Id = new Guid("19efdf76-6f4e-4db4-8606-7c2ab982ac9b"),
                            GiaBan = 0m,
                            MoTa = "にんい 洋服 ぐん ざぜん 評価 がいよう 馬 せっぷく がいよう ねんじゅう こうちょく 果てる 日欧 きゅうりょう 狂う とうき いく 遺失 復旧 かんぜん 不思議 全日本 さいほう 評価 つなひき 黒板 はちまき ぶそう こくみん じじょでん 日没 老齢 撃つ 閉じる 弱虫 きょうふ こうちょく 同僚 間隔 かい しょうがっこう ぼうず 抑制 減俸 ざんぴん 雑音 かんりょうてき 電話 貫く ことばつき.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Cotton Cheese"
                        },
                        new
                        {
                            Id = new Guid("99c78f04-9d0c-4131-a122-72616c20f90c"),
                            GiaBan = 0m,
                            MoTa = "かぜ はっぽう たいこうする りゅうこうご 伐採 店 老齢 こうつう 委員 はなはだ しょうじょう 終点 上手 店 一文字 せいぞう 〜亭 きもち あしくび 送る 液体 きょうき ぼくし ころす つぎつぎ えきびょう むく 十台 封筒 あらあらしい 山葵 出版 はんそう 入江 そあく 寮生 白菊 はんそう 上手 味噌 かんじる 十台 けいじばん かたみち きょうかい かぜ そあく こうせい 汚す 普及.",
                            SoLuongTon = 0,
                            TenSanPham = "Handmade Soft Soap"
                        },
                        new
                        {
                            Id = new Guid("a31d4559-9079-48b3-8173-520c8c8af1bd"),
                            GiaBan = 0m,
                            MoTa = "じじょでん じぞう ちゅうもんする あらあらしい まほうつかい もはん 上手 せっぷく どうけつ きょうき みなもと 面積 伐採 配慮 屈む 傑作 ひんきゃく ふん 電源 けしき 戦没 超〜 しあとるし おととい 〜系 のき 復旧 戦没 特殊 継承 浸す まもる 頂く かいたく はなぢ かい ぼくし きげんご かんそく 魔法 斬殺 金星 つなひき 渦巻き 消す 形 えきびょう 品詞 新婚旅行 かいじゅう.",
                            SoLuongTon = 0,
                            TenSanPham = "Practical Granite Car"
                        },
                        new
                        {
                            Id = new Guid("6d9a56f8-68d5-44eb-92b6-2ed35d8b54aa"),
                            GiaBan = 0m,
                            MoTa = "金 ころす やさしい けいかん 輸出 きょうき 救急車 けしき 浮世絵 軒 みさき 送る ほんらい 伐採 しゃこ 双 境 以下 つぎつぎ 抑制 廉価 都合 とちょう 徳川 電源 屈む 擬装 あびる もはん 始まる きょうはんしゃ ねんじゅう 差し上げる おんとう 活用 評価 はだか ちきゅう 店舗 九日 先週 じょうじゅん 救急車 老齢 こくふくする 奴ら たいりく ずいぶん みなと そだてる.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Concrete Chicken"
                        },
                        new
                        {
                            Id = new Guid("c94fbf04-0b7f-46db-8f2a-9428ddd6b44c"),
                            GiaBan = 0m,
                            MoTa = "せいしん ぶき うえる しょくん 無駄 りゃくず かんりょうてき まつり かん 量 斬殺 難しい せいぞう 好き 明治 隆起 はだか 騎兵 こくみん ふそく ぼくし ふん 〜系 じぶん 奴ら どろ ぐん 華やか せいかん ぶそう 差し上げる かっこう 重い 自宅 たれる 輸出 暇 備える くつじょく 運ぶ ごふく 超〜 ごうけん ぼきん 量 あらす ぼくし 提案する しゃっか きょだい.",
                            SoLuongTon = 0,
                            TenSanPham = "Tasty Steel Tuna"
                        },
                        new
                        {
                            Id = new Guid("32fb4a9c-a549-4914-83f0-8cd3f96fd517"),
                            GiaBan = 0m,
                            MoTa = "つうやく 安泰 遮断 浮世絵 評価 けいむしょ 避ける 機嫌 学者 ころす ぞくご きょうどう へいがい 床 はじめて 電話 杏 貫く ひんかく 乗せる じぶん 旧姓 しょうじょう 禍根 雇用 形 もうす 殺人者 ぶそう はなぢ 間隔 復旧 かいたく 済ます 無糖 せんじょうざい 春休み 左手 塾生 壮年 いじん たつ 検査 活用 施行 察知 馬 ほうせき たいこうする 薬.",
                            SoLuongTon = 0,
                            TenSanPham = "Small Soft Table"
                        },
                        new
                        {
                            Id = new Guid("3ea9290c-142a-4e13-b9bf-a13e4e2935ac"),
                            GiaBan = 0m,
                            MoTa = "むく ずいぶん ないしょばなし しゃくや おんとう かいたく きげんご 助手 金星 白菊 終点 かいぞく 助手 しずむ シアトルし 床 だいどころ 軒 急騰 漂う しょうじょう 徳川 先ず ひきざん 防犯 没落 うえる ちあん めいしょ 下さい 普及 学院 かんじる いう 超〜 ふん 仕方がない 凝固 すんか 評価 しゃくや 悲しみ かいぞく 凝固 重い じょうき 人性 手作り うえる やさしい.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Rubber Hat"
                        },
                        new
                        {
                            Id = new Guid("91f38fb1-89bd-475f-88ac-84ec805c6062"),
                            GiaBan = 0m,
                            MoTa = "勇気 老齢 先ず りょうど かつ かんそく はだか 奴ら 底 ほんらい 碁 じょうき 出かける 学院 つばさ 馬 とめる じじょでん そあく 譜面 とめる ぼくし 桜色 きげんご 山葵 たいさ 不健康 あおい 母 九日 活用 しばふ 暇 えきびょう いちだい とめる しゃっか ひんかく 問題 戦没 不可欠 人性 暇 賢明 あおい かぜ 復旧 もはん 送る 誤用.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Plastic Tuna"
                        },
                        new
                        {
                            Id = new Guid("32aa78bd-0099-41a5-ae21-73e080e873ab"),
                            GiaBan = 0m,
                            MoTa = "こいぬ じぞう あう つまる 誓い 雑音 ひきさく けいむしょ 消す 胃 店 十台 つまる 避ける かんどうする ちきゅう お盆 合う たれる かいたく あらす 病床 評価 あらす 零す こわす はだか せっぷく なおさら 禍根 そだてる 仕方がない 日欧 ぼうず あれる 半額 しょうじょう しょうかする しゅしょう にる しゅしょう 上手 つまる こはん 桜色 継承 かわかす よくげつ りゅうこうご つく.",
                            SoLuongTon = 0,
                            TenSanPham = "Sleek Rubber Shoes"
                        },
                        new
                        {
                            Id = new Guid("7b06842f-cc3c-417f-b5b5-50916cf81689"),
                            GiaBan = 0m,
                            MoTa = "おかね 屈む じぶん しゅしょう きょうしつ ちかく はなはだ ひきざん 漂う れつあく 不健康 哀れむ 送る さいぼう くつじょく 掛ける しょうじょう しょうゆ かん 原油 じじょでん 配慮 ちきゅう 左手 休日 学者 ころす いく たいさ 壊す あしくび ごうけん うえる 疾走 はっぽう 漂う 出版 やさい 電源 かいじゅう 評価 部首 暇 俵 終点 減俸 かん さくにゅう 約する つまる.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Granite Computer"
                        },
                        new
                        {
                            Id = new Guid("85b362fc-89fa-42f5-b11a-efb80f7d9daf"),
                            GiaBan = 0m,
                            MoTa = "たれる なおさら かいじゅう かいじゅう やさしい 無駄 かおつき 人性 宜しく 洋服 学者 まつ あらす 体重 母 つまる やさしい 自立 減俸 明治 せいしん 手作り 施行 迷路 きょうしつ 華やか 超〜 希望する 塾生 手作り ようい 塾生 以下 縛る ひんきゃく しょうりゃく 遮断 黒板 下着 にんい 平安 輸出 おかね 大仏 面積 ざぜん 騎兵 差し上げる かくじっけん あらあらしい.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Concrete Tuna"
                        },
                        new
                        {
                            Id = new Guid("a3dc3a4d-6edc-4a17-a9e9-6ec030a177c7"),
                            GiaBan = 0m,
                            MoTa = "あくれい じじょでん こうぞく 約する じじょでん きんく 好き きょうき 傑作 そんざい 不可欠 電話 憂い 零す けいじばん 徳川 既に おどろく 難しい かぶしきしじょう いつ頃 長唄 超音波 大仏 同僚 さきまわり 軒 大尉 切迫 きょうはんしゃ しゃっか 芸者 れつあく 迷路 あらそう あしくび まつ 人口 春休み 号 とりあえず 奇襲 はなぢ 機嫌 めいがら 好き ごふく お盆 むぼう 閉じる.",
                            SoLuongTon = 0,
                            TenSanPham = "Unbranded Cotton Chair"
                        },
                        new
                        {
                            Id = new Guid("9d90bcfc-6891-40f4-92cb-876074fe847a"),
                            GiaBan = 0m,
                            MoTa = "憂い 黙る 杏 機嫌 ちかく しょくん 歯を磨く あくれい 日没 ねばり 人口 こうぞく かっこう 話 賢明 しょうゆ もうす ことばつき 避ける 普及 あれる 色盲 はんだんする かわかす 白菊 おどろく 上手 施行 電話 りゅうこうご 高値 じょうじゅん かぜ しょうりゃく 失う 凝固 復旧 かくじっけん しずむ 伝統 ねばり 疾走 芽 つく じぶん 察知 絹糸 乗せる こうぞく 委員.",
                            SoLuongTon = 0,
                            TenSanPham = "Small Fresh Computer"
                        },
                        new
                        {
                            Id = new Guid("79ae7527-141c-4ae9-bba2-3ed255cf2e7b"),
                            GiaBan = 0m,
                            MoTa = "遮断 あびる かつ とうさん はっぽう 普及 こうせい 窒息 以下 こくみん 暇 俵 寮生 独裁 けいけんしゃ ことばつき 提案する 配慮 こうぞく ごうけん 委員 じぞう 不思議 じぎする あう 伝統 差し上げる たれる 徳川 春休み ことばつき 山葵 とふ しえんする ちかく 歯を磨く 窓 失う かちゅう けいかん 雑音 せんりゅう たて さきまわり 芸者 難しい かんじる いう もはん 浅い.",
                            SoLuongTon = 0,
                            TenSanPham = "Intelligent Fresh Bacon"
                        },
                        new
                        {
                            Id = new Guid("4ea9c069-ac5b-4286-9be7-7d6ddc7dde89"),
                            GiaBan = 0m,
                            MoTa = "うえる どろ じぞう 号 しょうゆ しばふ 天井 間隔 馬 むく 超音波 出版 すんか 待合 切迫 復旧 やさしい 唄う おきゃくさん 入江 ぼきん 防犯 誓い がんばる 投資 山葵 こくみん 賢明 下さい 学院 右利き 疾走 窒息 碁 うえる 急騰 当て字 日没 せいぞう 量 しあとるし とうき 学院 体重 地面 普及 じぎする 入江 大仏 げいひんかん.",
                            SoLuongTon = 0,
                            TenSanPham = "Ergonomic Granite Bacon"
                        },
                        new
                        {
                            Id = new Guid("2ea8a5d8-27df-4db7-b5e9-83cb15c1661c"),
                            GiaBan = 0m,
                            MoTa = "ちがい とりあえず かおつき にんい みなと こはん かぶしきしじょう 〜系 あっとうする かんどうする じじょでん 揺さぶる けいじばん 切迫 いたずら 書き方 飽くまでも 秘める 泳ぐ とめる ひかくする 窓 誓い かいぞく 無糖 けいじばん 検査 とりあえず やさい 検査 ぼきん ふん ちあん 九日 核実験 かっこう あう ぶっきょう 出版 うえる 投資 休日 ねんじゅう 〜系 明治 だくりゅう 堀川 同僚 液体 大仏.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Soft Keyboard"
                        },
                        new
                        {
                            Id = new Guid("de73e9df-a484-479a-a2e1-921accd7c77b"),
                            GiaBan = 0m,
                            MoTa = "さいばん きげんご つなひき 交錯 じぎする 割り箸 かっこう よわよわしい 隆起 ごふく 交錯 核実験 急騰 みさき じっかん ぼくし 浅い 退く 施行 じょうだん 先週 切迫 こはん 電話 継承 たいこうする きひん 貫く 壮年 果樹 しょうがっこう すんか 全日本 希望する よくげつ 天井 ほにゅうびん かんどうする ひがい 休日 牛乳 輸出 芸者 黙る 薬 馬鹿馬鹿しい 汚す 一文字 かんどうする 俵.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Fresh Pizza"
                        },
                        new
                        {
                            Id = new Guid("2d51acbe-7b4f-40fb-8c77-f0342a6564f9"),
                            GiaBan = 0m,
                            MoTa = "かいたく 凝固 隆起 〜亭 ほ ほうせき 防犯 恨み 超音波 遮断 丼 総括 かくじっけん りゃくず 備える 総括 ざぜん 評価 不健康 日欧 じょうだん たいさ フランス語 塾生 日没 手作り ほうげん ちかく たつ がんばる かんじる 恨み あらあらしい あう 宜しく 合う ほ 暴力 かんそく けいじばん まつり げんめつ とうさん くつじょく むこう むぜい いつ頃 かいぞく 送る せっぷく.",
                            SoLuongTon = 0,
                            TenSanPham = "Refined Concrete Shoes"
                        },
                        new
                        {
                            Id = new Guid("ef95f26a-ecd7-4909-b28a-792a040c8784"),
                            GiaBan = 0m,
                            MoTa = "塾生 とめる みつ 華やか 〜亭 ねんじゅう ぼうず 疾走 品詞 こうちょく みさき せいかん 超音波 じきしょうそう ほんらい 馬鹿馬鹿しい 殺人者 ふん 貫く 消す ころす ひかくする 入江 当て字 むこう こうつう あびる 無糖 こうつう 徳川 えきびょう めいし 羊毛 けいむしょ 誘惑 お盆 先ず きょだい 魔術 老齢 魔法 宜しく いう 下着 老齢 洋服 ふん ちきゅう ぞくご 塾生.",
                            SoLuongTon = 0,
                            TenSanPham = "Sleek Frozen Computer"
                        },
                        new
                        {
                            Id = new Guid("2b867c98-c6ec-4c9a-99bf-a81c816e8ca5"),
                            GiaBan = 0m,
                            MoTa = "こはん 仕方がない はじめて 切迫 馬鹿馬鹿しい じきしょうそう 汚す 憂い この頃 靖国神社 液体 継承 やさい 軒 こうおつ こわす 大尉 右利き 双 仕事 無駄 弥生 めいし けしき 喜劇 救急車 面 憂い 核実験 寮生 徳川 ずいぶん しょうりゃく みなもと そあく ぶん 休日 いっさくじつ かん 超〜 悲しみ 魔術 れつあく 芸者 双 じぞう 大仏 たらす 委員 伝統.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Concrete Cheese"
                        },
                        new
                        {
                            Id = new Guid("e96c09b6-21db-4ef4-90b1-4dd39c8ba613"),
                            GiaBan = 0m,
                            MoTa = "ぶっきょう みなと 殺人者 はっぽう ねんじゅう すんか じっかん えきびょう つなひき ぼうず さいほう むらさきいろ 〜系 はんそう ぶっきょう きょうはんしゃ 閉じる ふかさ きいろ 漠然 旧姓 フランス人 しょうゆ かい きょうき しえんする 暇 活用 つまる 平安 いちだい 学者 始まる 出版 店 米兵 助手 かん 鈍器 喜劇 たくす しゃっか 賢明 じょうじゅん 撃つ きひん 傑作 脱税 禍根 さいぼう.",
                            SoLuongTon = 0,
                            TenSanPham = "Refined Cotton Bike"
                        },
                        new
                        {
                            Id = new Guid("0564c8f6-530d-4e5f-a9be-f59d6a833daf"),
                            GiaBan = 0m,
                            MoTa = "運ぶ けいじばん 窒息 縛る 金 無駄 江戸 人性 品詞 とめる 不思議 味噌 境 あらそう たつ ふそく いちだい ちきゅう 牛乳 ほ 下着 殻 洋服 黒板 あびる きょうどう どうけつ ほ 問題 あう めいしょ 脱税 半額 人口 〜亭 この頃 かんりょうてき かんしん ひがい 血液 靖国神社 飽くまでも 無糖 ようい 始まる 奇襲 塾生 せっぷく 左手 間隔.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Soft Ball"
                        },
                        new
                        {
                            Id = new Guid("f85b5190-50c7-4d65-b0b2-05b44b3a3b01"),
                            GiaBan = 0m,
                            MoTa = "面積 つまる はんだんする 上手 出版 品詞 じょうじゅん はんそう 九日 むく あらあらしい たれる 徳川 施行 くつじょく やさしい さいぼう 禍根 部首 桜色 たて ひがい ごうけん 差し上げる ししょく 問題 きゅうりょう ざんぴん 羊毛 杏 減俸 ないしょばなし 母 きげんご ざぜん きんく 地面 じっかん 指紋 ぼくし 自立 人性 退く 渦巻き 店 漂う 見当たる けいむしょ 見当たる じょうだん.",
                            SoLuongTon = 0,
                            TenSanPham = "Incredible Plastic Cheese"
                        },
                        new
                        {
                            Id = new Guid("962c406f-d36b-4209-931a-a49b584be5a1"),
                            GiaBan = 0m,
                            MoTa = "縛る 切迫 たて 提案する ひきさく むく 左手 誤用 親切 江戸 かんじる おんとう あらあらしい 間隔 きひん 人口 馬 白菊 しきもう つぎつぎ 下さい 誤用 むぜい むぼう けいけんしゃ 不可欠 そあく こわす 活用 人口 避ける かぜ こくふくする 救急車 撃つ 避ける いう 長唄 底 せいじょう いたずら 窒息 面積 りゅうこうご さいばん 報じる 掛ける 品詞 かんそく きゅうりょう.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Cotton Cheese"
                        },
                        new
                        {
                            Id = new Guid("6e8c0758-76f1-43a5-b165-8f07b07110d3"),
                            GiaBan = 0m,
                            MoTa = "じぞう みつ 隆起 米国 魔術 施行 隆起 ひんきゃく 近視 ちらかす 休日 まぎらす たくす 評価 封筒 雑音 果樹 洋服 ちがい つまる いつ頃 都合 きゅうりょう ざぜん こわす よくげつ ひきざん 平安 機嫌 せんたくする 金縛り かちゅう ことばつき 抑制 ぐん 迷路 なおさら 九日 ころす 金星 ちょさくけん かつ 大尉 きょうはんしゃ はだか うえる ほにゅうびん あらす 果てる ことばつき.",
                            SoLuongTon = 0,
                            TenSanPham = "Sleek Concrete Cheese"
                        },
                        new
                        {
                            Id = new Guid("cb1e8602-dbec-46fa-9c16-e213270d3293"),
                            GiaBan = 0m,
                            MoTa = "乗せる 問題 すんか 揺さぶる 地面 全日本 ゆるむ こうおつ みさき せんじょうざい だいどころ だくりゅう 普及 さきまわり 浸す よくげつ 〜亭 超音波 フランス語 まつ ざぜん おきゃくさん はちまき 面積 はんだんする 窒息 色盲 奇襲 たいりく さいぼう 九日 せんりゅう よぼう ほ 塾生 喜劇 かわかす まぎらす 秘める 旧姓 さいぼう 委員 明治 うえる 底 果樹 じきしょうそう 伝統 りょうど にんい.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Fresh Tuna"
                        },
                        new
                        {
                            Id = new Guid("9b0bcd82-a47b-4cb9-a18e-4f40af65fd61"),
                            GiaBan = 0m,
                            MoTa = "金縛り 閉める 浸す 遺失 先週 継承 ひきざん 老齢 はちまき 減俸 品詞 推奨 徳川 はじめて めいがら じゅうどう 春休み 勇気 こはん むく きょうどう こうせい ししょく 乗せる あらす しゅしょう 店舗 以下 せいかん 独裁 あう ちきゅう 馬 春休み 超音波 しゃくや じじょでん りょうど たまご 浸す 無糖 つうやく ちがい みなと さいぼう 学者 むく 上手 助手 しょうじょう.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Fresh Bacon"
                        },
                        new
                        {
                            Id = new Guid("763eca15-659e-44ce-927b-6aadf31c2dd8"),
                            GiaBan = 0m,
                            MoTa = "おどろく たいこうする 色盲 めいがら むく 勇気 ふくへい さくにゅう 救急車 活用 右利き お盆 閉める 不思議 不思議 全日本 やさしい つうやく ふん 消す はりい ずいぶん 白菊 あつい とりあえず ちらかす そんざい かぶしきしじょう 避ける にんい ぶき 安泰 みさき ちがい 喜劇 運ぶ 合う じぎする くつじょく ちきゅう 希望する 浮世絵 ぶき 復旧 おんとう 春休み たれる ざんぴん せっぷく そだてる.",
                            SoLuongTon = 0,
                            TenSanPham = "Tasty Soft Chicken"
                        },
                        new
                        {
                            Id = new Guid("f46d4d2b-db80-44b7-9396-414e261f5e19"),
                            GiaBan = 0m,
                            MoTa = "廉価 継承 金星 ちあん よくげつ 避ける 上手 じょうだん 〜系 フランス語 迷路 こうちょく すんか きょだい しょうゆ 馬 ぶき 特殊 誤用 都合 廉価 ぶん 減俸 復旧 揺さぶる だくりゅう 斬殺 まもる おきゃくさん 喜劇 碁 品詞 哀れむ ゆるむ 推奨 お盆 撃つ 形 縛る とちょう みつ ごふく つく ほうせき そんざい まぎらす 急騰 やしなう 窓 とふ.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Wooden Fish"
                        },
                        new
                        {
                            Id = new Guid("6f5878ee-7a3d-4265-bc24-d7b152c3fcf9"),
                            GiaBan = 0m,
                            MoTa = "かおつき しゅしょう はんそう ほうしゅう へいがい 右利き 陳列室 かぶしきしじょう さきまわり 間隔 難しい 店舗 いじん 寮生 まほうつかい しょうりゃく 唄う さいぼう 店舗 伝統 どろ 仕事 ねんじゅう 品詞 店舗 ぶっきょう 傑作 鍋 さいばん 推奨 体重 ひきさく 境 きんく 希望する 切迫 こいぬ 不健康 出かける 交錯 果樹 はじめて 希望する 誘惑 そあく 休日 ほ 洋服 やさい たれる.",
                            SoLuongTon = 0,
                            TenSanPham = "Intelligent Soft Shirt"
                        },
                        new
                        {
                            Id = new Guid("dd29f7d4-f3d2-49b7-a8be-a85432dcaa1e"),
                            GiaBan = 0m,
                            MoTa = "にる 伐採 縛る 馬鹿馬鹿しい 長唄 かっこう とくに 色々 たいさ 唄う とくに 総括 しえんする ちえん 一文字 〜亭 はなぢ 芽 丼 難しい 警官 めいがら 俵 じっかん 体重 魅力 かつ たいさ あくれい 親切 かんりょうてき 希望する 魅力 犠牲 自宅 ちえん 明治 長唄 日没 指紋 かくじっけん そだてる 難しい こうせい フランス人 げんめつ 犠牲 普及 核実験 屈む.",
                            SoLuongTon = 0,
                            TenSanPham = "Handmade Cotton Chips"
                        },
                        new
                        {
                            Id = new Guid("657f23ed-6673-4277-9b09-9fbb7183666f"),
                            GiaBan = 0m,
                            MoTa = "あらあらしい しえんする 壊す ぼくし 一文字 見当たる 形 みなと みなもと もうす ほんらい じょうだん じじょでん せいしん ひきさく 禍根 はちまき のき 零す かいたく 自立 賢明 疾走 たつ どろ 電話 きょうしつ にんい みつ ぐん たいさ 軒 誘惑 窓 旧姓 喜劇 手作り 零す こうつう れつあく 電話 ちょさくけん ハチのす 牛乳 うんがいい 靖国神社 まもる 大丈夫 渦巻き しょうかする.",
                            SoLuongTon = 0,
                            TenSanPham = "Unbranded Plastic Cheese"
                        },
                        new
                        {
                            Id = new Guid("e3362938-d1be-4a88-bfc8-b60fe8865c7f"),
                            GiaBan = 0m,
                            MoTa = "米国 むぼう さいばん 牛乳 渦巻き むこう いく しえんする 撃つ 病床 ちかく ひがい げんめつ りゃくず ねばり 体重 かいじゅう しょうじょう どうけつ ちゅうもんする 先週 華やか 始まる かんどうする あしくび 投資 見当たる 差し上げる どろ ねばり 境 俵 きょうふ かいぞく きょうふ 旧姓 みなもと めいし 江戸 唄う 太る えきびょう 済ます 貫く 魔法 りゃくず のき 始まる ほうしゅう とめる.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Rubber Bike"
                        },
                        new
                        {
                            Id = new Guid("f090572c-966c-411e-b6d4-115e02962e05"),
                            GiaBan = 0m,
                            MoTa = "高値 ぼくし 廃墟 牛乳 ゆるむ 防犯 あびる 店 たて 暇 左手 たて たいやく しょうかする 活用 独裁 安泰 ハチのす たいやく 報じる 減俸 おととい 十台 いつ頃 廉価 ぶそう こうせい きゅうりょう 投資 いじん 長唄 形 弱虫 自宅 江戸 封筒 ちゅうもんする こくふくする しきもう 馬鹿馬鹿しい いう むぜい ふくへい どうけつ 狂う りゅうこうご 塾生 戦没 せいかん 面積.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Steel Salad"
                        },
                        new
                        {
                            Id = new Guid("dc07b6e4-eb92-4cd3-9270-46fc549c9004"),
                            GiaBan = 0m,
                            MoTa = "ごじゅう 店舗 のき えきびょう 天井 宜しく せいじょう 禍根 輸出 不健康 江戸 底 超音波 ほうしゅう よくげつ 旧姓 誤用 活用 超〜 かたみち 退く 太る ぼくし いっさくじつ 学院 塾生 いっさくじつ ほんらい たくす 軒 むぜい 施行 零す はちのす ざぜん ふさい 施行 出かける しきもう 血液 さくにゅう たいさ たくす 漠然 みなもと 馬 あっとうする 号 きょうしつ 不可欠.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Rubber Pants"
                        },
                        new
                        {
                            Id = new Guid("295f2c69-b92f-40c7-985e-22d07f0da374"),
                            GiaBan = 0m,
                            MoTa = "秘める シアトルし 総括 杏 ごうけん かつ とりあえず 貫く 原油 はっぽう どうけつ 米兵 縛る 米国 施行 運ぶ かたみち フランス人 俵 ころす しょうりゃく ころす ちあん ふさい 妥協する 安泰 軒 そだてる 金星 杏 牛乳 誘惑 色盲 十台 こうせい こいぬ のき しょうゆ 核実験 話 たいりく 凝固 閉める 閉じる たくす うえる つく つなひき 終点 にんい.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Plastic Gloves"
                        },
                        new
                        {
                            Id = new Guid("2f95194b-2071-4621-b28c-5c8d9d49bf57"),
                            GiaBan = 0m,
                            MoTa = "かんしん あおい めいがら きもち 脱税 しょうがっこう 歯を磨く ざぜん 普及 とうき 救急車 勇気 いっさくじつ めいし しえんする 天井 人性 色々 にんい 譜面 店 下着 奴ら 賢明 いじん 電話 きんく あらす 床 りょうど ちらかす 不健康 憂い ふそく しょうゆ 魔術 かんそく 大丈夫 りゃくず むこう 自立 始まる かくじっけん 都合 先ず 零す かおつき りょうど 機嫌 狂う.",
                            SoLuongTon = 0,
                            TenSanPham = "Tasty Rubber Chips"
                        },
                        new
                        {
                            Id = new Guid("a6cb1577-9603-4491-937e-99869ed62e1b"),
                            GiaBan = 0m,
                            MoTa = "よわよわしい 漂う 脱税 平安 上手 日没 十台 弥生 狂う かわかす 〜亭 奉仕 ねんじゅう 日欧 乗せる あつい とちょう いたずら 〜系 面積 しょうがっこう りゃくず こうせい 同僚 一文字 品詞 洋服 日没 恨み 抑制 ぶっきょう 長唄 投資 まつり つうやく 奴ら 明治 はちのす 陳列室 徳川 仕方がない 難しい こはん ほんらい 部首 とめる 遺失 店舗 安泰 こくふくする.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Concrete Pants"
                        },
                        new
                        {
                            Id = new Guid("7087b96d-3969-41fe-9f1c-9888d70bbef5"),
                            GiaBan = 0m,
                            MoTa = "不可欠 ほ りょうど ぶん 底 果樹 魅力 馬 かんぜん たらす おきゃくさん 学院 たまご じぎする きょうどう かんしん がんばる たいさ 遮断 評価 斬殺 かおつき 戦没 フランス語 暇 めいがら けしき 推奨 秘める 禍根 まほうつかい 戦没 あしくび 無糖 太る きもち 無駄 下着 けいけんしゃ 賢明 こいぬ 米国 きょうき 好き 減俸 仕事 はなぢ きゅうりょう つなひき 右翼.",
                            SoLuongTon = 0,
                            TenSanPham = "Intelligent Plastic Chicken"
                        },
                        new
                        {
                            Id = new Guid("144fcc77-1401-4349-abfd-5f4c68a85f2b"),
                            GiaBan = 0m,
                            MoTa = "おりめ 以下 春休み じょうき がんばる しょうりゃく 貫く 大尉 げんめつ 絹糸 弱虫 おりめ じょうだん 高値 殺人者 伐採 近視 じきしょうそう はりい 手作り 以下 避ける むぼう さきまわり 縛る しきもう ぶん めいがら ひかくする 太る 廃墟 ひかくする かつ けいじばん たいりく みつ つうやく けいかん うえる 宜しく ふかさ むこう じゅうらい 安泰 ねばり しばふ 頂く たいりく 洋服 失う.",
                            SoLuongTon = 0,
                            TenSanPham = "Unbranded Plastic Pizza"
                        },
                        new
                        {
                            Id = new Guid("012b5786-7fb0-4009-b256-ad19944a12ae"),
                            GiaBan = 0m,
                            MoTa = "ざぜん 窒息 十台 逆 はなじ 大丈夫 たいりく 誘惑 浅い 学院 色々 ぼくし ひきざん 難しい むく そあく 送る 雑音 ほうしゅう じょうき りょうど 日没 閉める かいぞく 誤用 廉価 殻 すいせん 先週 たいりく とりあえず 始まる 馬 むらさきいろ 黙る 窒息 ぶん 店 見当たる 報じる 号 いつ頃 量 れつあく せんりゅう じじょでん いう 馬 狂う 魔法.",
                            SoLuongTon = 0,
                            TenSanPham = "Small Concrete Pants"
                        },
                        new
                        {
                            Id = new Guid("66ef17d3-a2a0-49dd-8fa3-cb22cef29ca8"),
                            GiaBan = 0m,
                            MoTa = "おととい かんそく ひがい ひきざん よわよわしい かいじゅう 不健康 長唄 病床 かんそく 浸す めいしょ 金縛り きょうどう 牛乳 右利き まほうつかい 疾走 しょうりゃく 金星 しあとるし たいりく 母 おととい はりい とりあえず 新婚旅行 じょうだん かわかす 明治 じじょでん 伝統 ちらかす 失う いたずら 待合 悲しみ 悲しみ 約する 馬鹿馬鹿しい はなぢ 礎 あっとうする 急騰 しょうじょう 自宅 〜亭 恨み ぼきん じきしょうそう.",
                            SoLuongTon = 0,
                            TenSanPham = "Intelligent Plastic Ball"
                        },
                        new
                        {
                            Id = new Guid("4add607e-e33f-41ce-a7dd-bf1fb05ae852"),
                            GiaBan = 0m,
                            MoTa = "不可欠 けいむしょ 交錯 ちかく 妥協する せっぷく 哀れむ 飽くまでも はなじ きょうはんしゃ 悲しみ 電話 しばふ 米兵 みさき きいろ 迷子 備える 傑作 誘惑 日没 没落 お盆 ちゅうもんする 仕方がない 体重 金縛り 俵 切迫 ごふく あれる かつ ぶん 貫く 全日本 縛る 堀川 量 ふかさ せいかん まつり シアトルし 間隔 まほうつかい 施行 ひがい ほにゅうびん つばさ いっさくじつ ぼうず.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Soft Bike"
                        },
                        new
                        {
                            Id = new Guid("426a5d46-102c-44aa-96c7-9fa40705919e"),
                            GiaBan = 0m,
                            MoTa = "ちえん 品詞 脱税 きょうしつ けいじばん いっさくじつ ぶき ふさい 壊す はっぽう 馬 かんじる 超音波 半額 奉仕 魔術 つうやく 出版 かい ぶっきょう 憂い かぜ ぞくご 平安 封筒 しゃっか 店舗 魅力 誘惑 警官 推奨 むく あびる たて かんしん 手作り 消す 丼 床 不可欠 薬 せんりゅう くつじょく 馬 掛ける 靖国神社 たくす 開閉 りょうど おかね.",
                            SoLuongTon = 0,
                            TenSanPham = "Incredible Fresh Salad"
                        },
                        new
                        {
                            Id = new Guid("b59859df-0fe3-423b-ad64-2920f577fc02"),
                            GiaBan = 0m,
                            MoTa = "掛ける 提案する 地面 上手 せんじょうざい 馬 みなと あおい 宜しく ほ 唄う じぞう ぶっきょう たいこうする ごうけん ひがい ふさい ざんぴん ちゅうもんする かたみち 提案する きげんご ふさい とめる 弱虫 むらさきいろ 重い 胃 乗せる めいがら 浮世絵 哀れむ 双 太る せんじょうざい ごふく ぼきん まつ 出かける 話 先ず ほ まほうつかい ししょく 手作り めいしょ はりい 機嫌 とうさん せっぷく.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Fresh Bacon"
                        },
                        new
                        {
                            Id = new Guid("a835d51a-b29f-45d6-a035-7d5171aad78c"),
                            GiaBan = 0m,
                            MoTa = "羊毛 特殊 色盲 絹糸 秘める 擬装 けいむしょ ゆるむ あらあらしい 誓い ちがい 失う りゃくず 活用 迷路 よぼう せいしん 不可欠 施行 じょうじゅん とちょう 泳ぐ しあとるし かたみち 推奨 仕方がない 人性 きょうしつ 零す たいやく むく 約する かおつき 芸者 あつかい さいぼう 報じる 桜色 ふん 妥協する たいさ あしくび けいむしょ こうせい ぶん 暴力 ごふく ねばり はんだんする じょうき.",
                            SoLuongTon = 0,
                            TenSanPham = "Handmade Frozen Ball"
                        },
                        new
                        {
                            Id = new Guid("b83eddaa-f17d-4c62-b1a3-886385fa897d"),
                            GiaBan = 0m,
                            MoTa = "はりい 面積 きょうかい はなはだ 入江 がいよう 安泰 りゃくず しずむ 漠然 この頃 汚す 戦没 委員 高値 だいどころ よぼう 大仏 よぼう かんりょうてき こくみん 奇襲 ころす はなぢ みなもと 漂う 委員 入江 さきまわり きゅうりょう むぼう たくす 無駄 学者 ひんきゃく こはん 誘惑 浸す 差し上げる ごふく 日欧 賢明 たくす せんりゅう 退く 都合 つばさ あらそう 奴ら 合う.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Wooden Bacon"
                        },
                        new
                        {
                            Id = new Guid("e44307d7-886d-441f-9bfb-368ba3647095"),
                            GiaBan = 0m,
                            MoTa = "ほうせき 恨み 魔法 掛ける 誤用 たらす 推奨 しょくん 秘める しょうかする 切迫 恨み きょうはんしゃ 羊毛 軒 始まる 日没 つく こうちょく ぼきん 号 賢明 華やか 面 一文字 ちょさくけん 報じる うえる どうけつ 避ける はりい 哀れむ 丼 都合 けいかん かん 話 無駄 先週 天井 斬殺 重い こくふくする 不思議 がんばる こうぞく 疾走 いじん あれる きょうふ.",
                            SoLuongTon = 0,
                            TenSanPham = "Sleek Plastic Shirt"
                        },
                        new
                        {
                            Id = new Guid("d63745cc-c683-4b21-a26c-341829ae02fc"),
                            GiaBan = 0m,
                            MoTa = "せんじょうざい かくじっけん 出版 シアトルし 靖国神社 ようい じぶん かぜ 鍋 めいしょ 迷子 下さい シアトルし 金縛り がいよう こうせい 〜系 おりめ 無糖 つなひき ぐん 馬鹿馬鹿しい あらす せいぞう 床 出かける せんじょうざい こくふくする そだてる よくげつ めいがら 提案する 日欧 かおつき ぶん しゃっか 以下 さいばん 施行 絹糸 閉める しょうりゃく しょくん もはん 送る 色々 寮生 委員 はっぽう かいたく.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Plastic Ball"
                        },
                        new
                        {
                            Id = new Guid("0a1d68ee-a835-48c9-bb41-5ab40db852ea"),
                            GiaBan = 0m,
                            MoTa = "終点 はりい しあとるし 遺失 むこう 下着 既に しえんする 靖国神社 むらさきいろ みなもと 廃墟 とうき 浅い たまご しゃっか 境 じぎする 体重 りゅうこうご 復旧 手作り とりあえず だいどころ しえんする 遺失 じっかん 全日本 いう 面積 どろ 果樹 馬 ふそく 血液 おんとう よわよわしい げいひんかん 果てる 地面 はちのす ひきさく 遮断 たいこうする 勇気 救急車 約する せいしん かちゅう ひかくする.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = new Guid("2435dbd9-bf3c-48dd-836c-a2890efe374f"),
                            GiaBan = 0m,
                            MoTa = "こうせい 壊す 全日本 ねんじゅう 九日 俵 救急車 さくにゅう ほんらい ほ まほうつかい ハチのす 禍根 失う 高値 しょうじょう ふかさ しあとるし ごうけん 零す 馬 あらす 色盲 合う 合う いじん とちょう 揺さぶる 浮世絵 秘める めいしょ 仕事 無糖 提案する 下さい 宜しく 投資 終点 大尉 始まる 靖国神社 避ける そあく 芸者 黙る 果樹 げんめつ とくに 始まる かんぜん.",
                            SoLuongTon = 0,
                            TenSanPham = "Refined Metal Fish"
                        },
                        new
                        {
                            Id = new Guid("6cc4bd10-6789-4134-ae85-36657a7a7a8e"),
                            GiaBan = 0m,
                            MoTa = "ハチのす 暴力 へいがい 新婚旅行 ハチのす 量 きもち 暇 騎兵 量 しょうりゃく 交錯 秘める ようい 血液 じょうじゅん おかね ちゅうもんする ちゅうもんする せいかん あっとうする 機嫌 きいろ がんばる そあく かいぞく 恨み 味噌 母 洋服 靖国神社 おきゃくさん 開閉 助手 じっかん ぶそう はりい 出かける 迷子 同僚 寮生 かんじる かくじっけん とふ 奴ら 推奨 仕事 号 出版 誤用.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Wooden Ball"
                        },
                        new
                        {
                            Id = new Guid("5eda2955-a8e0-42a3-84f0-1ba4f9276f12"),
                            GiaBan = 0m,
                            MoTa = "機嫌 巡回 れつあく 手作り ふそく しょうがっこう 渦巻き じっかん 掛ける こわす 逆 あれる 開閉 助手 ぶき しょくん 仕事 狂う じきしょうそう やさしい ちきゅう 九日 ほんらい 十台 ざんぴん あくれい 殻 きょだい 終点 かわかす 大仏 電話 人口 めいし 輸出 色々 じぞう りょうど 母 母 当て字 けいじばん 検査 奴ら かつ 〜亭 ちゅうもんする 薬 たくす たまご.",
                            SoLuongTon = 0,
                            TenSanPham = "Incredible Concrete Table"
                        },
                        new
                        {
                            Id = new Guid("45745fd8-b10d-4f6f-b44d-665df44721f6"),
                            GiaBan = 0m,
                            MoTa = "自立 ぼくし 下さい 陳列室 ぼうず あつかい 歯を磨く せいしん しゅしょう フランス語 もはん せいじょう 妥協する じっかん シアトルし あつい あらあらしい たまご 大丈夫 がいよう 殻 のき 羊毛 ちかく 軒 活用 好き 警官 せんじょうざい たらす かんどうする 徳川 果樹 せんりゅう せいぞう きひん なんべい むらさきいろ 継承 はなはだ 雑音 めいしょ かちゅう つばさ 運ぶ 暇 たいやく きいろ ふん おんとう.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Granite Bacon"
                        },
                        new
                        {
                            Id = new Guid("eaaf1e2f-3ec4-42af-a384-e7c9b6f24e5b"),
                            GiaBan = 0m,
                            MoTa = "ないしょばなし げんめつ こうおつ しゃくや 金 遮断 送る せんたくする ごうけん 華やか ひんきゃく ぐん ぐん 日没 かんそく かつ 飽くまでも 親切 済ます 漂う はりい はだか ひんかく 馬鹿馬鹿しい 一文字 恨み いく 運ぶ 脱税 ひきざん 唄う 面積 江戸 華やか 暴力 かいじゅう 伝統 消す えきびょう 原油 いちだい 封筒 まもる かんどうする 屈む 量 みなもと 浮世絵 継承 電話.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Frozen Chips"
                        },
                        new
                        {
                            Id = new Guid("d47c7060-59d0-4282-be26-8a10738dcb4f"),
                            GiaBan = 0m,
                            MoTa = "どうけつ げいひんかん かんしん 浸す 液体 狂う きょうどう にんい 斬殺 にる あつい こいぬ 核実験 いく ごうけん ぶき 壮年 せんたくする 始まる 無糖 ぶき せっぷく とうさん 特殊 おどろく おどろく 九日 こうおつ あらあらしい ひんかく じぞう 迷路 雑音 機嫌 あう はりい 好き ひきざん ほうせき そんざい がいよう 約する 黒板 先ず 間隔 弥生 陳列室 既に 零す ざぜん.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Soft Cheese"
                        },
                        new
                        {
                            Id = new Guid("c2c39541-7fed-4efd-a055-0dcf54a9b613"),
                            GiaBan = 0m,
                            MoTa = "つく 不健康 色盲 おかね 助手 脱税 とちょう かおつき 当て字 ふさい けいじばん だくりゅう 黒板 のき 仕方がない 魅力 済ます 大仏 みなもと 不可欠 かおつき 屈む 当て字 かいたく 芸者 かくじっけん おんとう 礎 はなじ あらあらしい 汚す さくにゅう むく 一文字 羊毛 壮年 あくれい しばふ 左手 零す 馬鹿馬鹿しい 救急車 ぼきん 避ける 遮断 誓い あらそう 哀れむ 部首 とめる.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Soft Mouse"
                        },
                        new
                        {
                            Id = new Guid("1c492bad-6856-4d18-b5eb-0bc3fa2f4f0a"),
                            GiaBan = 0m,
                            MoTa = "急騰 ちょさくけん 浸す 果樹 そんざい 合う 下着 迷路 味噌 江戸 かぜ 配慮 かん 誓い くつじょく ころす 零す 継承 はちまき じょうだん こくみん さきまわり いう 江戸 無駄 めいし はちまき 傑作 高値 浅い 量 おりめ うえる 間隔 交錯 軒 ちあん 縛る 新婚旅行 切迫 はなじ 奇襲 秘める むこう よくげつ 羊毛 とめる じぎする しあとるし たつ.",
                            SoLuongTon = 0,
                            TenSanPham = "Ergonomic Plastic Towels"
                        },
                        new
                        {
                            Id = new Guid("70f7984a-68aa-475d-9115-c876b3f38b6f"),
                            GiaBan = 0m,
                            MoTa = "せいぞう 独裁 じぎする 壊す あつかい そだてる しゃっか 零す めいがら 地面 割り箸 はちのす 傑作 屈む 以下 じょうき 不可欠 きんく たいさ 零す 遮断 くつじょく 運ぶ 普及 こうせい 電源 あっとうする 号 ふん げんめつ 塾生 つぎつぎ 宜しく 推奨 地面 ちきゅう どろ 壊す いちだい かん しょうかする 右翼 ないしょばなし ふん たれる 〜系 あらす 見当たる つく 減俸.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Plastic Soap"
                        },
                        new
                        {
                            Id = new Guid("667fdd58-a921-45a9-95cc-59712aef753d"),
                            GiaBan = 0m,
                            MoTa = "こうつう 間隔 あびる 消す ひきさく 天井 備える きょだい ふさい おきゃくさん 閉める 検査 しょくん とふ むらさきいろ 浮世絵 つなひき おととい 胃 送る きょだい 犠牲 かいたく おかね 果てる 恨み 終点 かちゅう りゅうこうご 休日 廃墟 しょうじょう つばさ かんぜん もうす 安泰 ごじゅう ぶっきょう ふさい この頃 かんじる くつじょく 飽くまでも ぶっきょう 渦巻き とちょう じゅうどう 黙る おどろく せいしん.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Cotton Car"
                        },
                        new
                        {
                            Id = new Guid("8271b6ca-07ab-407c-bf25-a8f93665dc38"),
                            GiaBan = 0m,
                            MoTa = "間隔 伝統 白菊 まぎらす 部首 鍋 遮断 雇用 隆起 金 こうつう ざぜん 割り箸 かんじる 堀川 いっさくじつ 暇 浸す 総括 無糖 防犯 丼 継承 のき 唄う ふかさ せっぷく 救急車 ようい 逆 けいむしょ この頃 店 ほうげん きょだい とくに 譜面 ひがい 浮世絵 おきゃくさん 雑音 譜面 ねばり ひかくする 左手 けしき 希望する 血液 俵 にる.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Frozen Bacon"
                        },
                        new
                        {
                            Id = new Guid("cada3c78-1f1e-4e1a-9b8c-ae9195ccc34d"),
                            GiaBan = 0m,
                            MoTa = "すいせん やさい 廉価 金縛り こいぬ 隆起 ふさい しゃっか にる あらす けいけんしゃ 活用 底 ししょく あしくび 運ぶ たくす 漂う 復旧 学院 きょうかい 明治 殻 ほうしゅう 形 とふ あしくび 備える つまる うえる 機嫌 弱虫 話 核実験 哀れむ おかね 掛ける 雑音 洋服 げいひんかん こうおつ 核実験 げいひんかん 待合 不健康 汚す けいじばん かおつき 恨み ころす.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Metal Soap"
                        },
                        new
                        {
                            Id = new Guid("857b46d9-8f74-4ea8-adc3-edda84ad03df"),
                            GiaBan = 0m,
                            MoTa = "賢明 壊す 大丈夫 とうさん まつ かんりょうてき 出かける たいやく 窓 たいさ 終点 号 不可欠 人口 狂う 体重 救急車 こうつう 恨み 色盲 禍根 封筒 かいたく あっとうする 雑音 げんめつ この頃 こわす 窒息 送る ぶそう 凝固 伝統 かいたく 無糖 ほ 色々 封筒 つばさ しょうゆ 陳列室 学院 地面 活用 おきゃくさん やさしい 果てる つまる 誓い 逆.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Fresh Shoes"
                        },
                        new
                        {
                            Id = new Guid("20828531-8f4a-46cc-a2c5-1a8d4b2a3bd8"),
                            GiaBan = 0m,
                            MoTa = "仕方がない しょうじょう 不可欠 下着 掛ける ごじゅう じゅうらい きょうかい かくじっけん ぼきん 評価 〜亭 かたみち 渦巻き いじん 抑制 ぶき りょうど 面 機嫌 えきびょう おととい 封筒 なんべい 芸者 礎 太る 約する しずむ ふそく うんがいい ひがい ふくへい 誘惑 迷子 切迫 委員 減俸 あれる 勇気 誓い たらす たまご ちえん 出版 牛乳 かんそく 弱虫 かいじゅう 漂う.",
                            SoLuongTon = 0,
                            TenSanPham = "Refined Metal Gloves"
                        },
                        new
                        {
                            Id = new Guid("449513e1-c8a7-479a-99ba-014b6e2c1007"),
                            GiaBan = 0m,
                            MoTa = "長唄 おととい ふくへい きょだい きょうしつ さいぼう 隆起 ほうげん ごふく はなはだ 割り箸 輸出 めいしょ 絹糸 かわかす 脱税 ひんきゃく かっこう 防犯 むぼう みなと こうせい しえんする 形 巡回 病床 たいやく ぶそう 備える はりい 店 殻 活用 ねばり こうちょく きょだい 病床 悲しみ 俵 むく 魔法 頂く かおつき 泳ぐ 騎兵 間隔 きんく せいぞう 察知 不思議.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Frozen Chips"
                        },
                        new
                        {
                            Id = new Guid("2460a04f-83b3-4652-8a52-67960ed6e009"),
                            GiaBan = 0m,
                            MoTa = "不可欠 希望する おきゃくさん くつじょく もはん けしき 同僚 全日本 しゃこ さいほう あびる かいじゅう 十台 ねんじゅう まもる 原油 汚す 逆 済ます きもち たつ 犠牲 かっこう しずむ じきしょうそう 仕方がない けいけんしゃ 底 下着 恨み 壊す 奉仕 備える 誓い 掛ける 継承 いたずら 出かける かん 無駄 体重 靖国神社 ふん 桜色 こうぞく みさき ねんじゅう ひきざん 金 胃.",
                            SoLuongTon = 0,
                            TenSanPham = "Tasty Metal Mouse"
                        },
                        new
                        {
                            Id = new Guid("31c9d4b7-7b7c-4104-8f3c-8835c7bf1e46"),
                            GiaBan = 0m,
                            MoTa = "宜しく つうやく きゅうりょう 斬殺 ごじゅう 洋服 ぶそう いっさくじつ かわかす 自立 たいやく きもち 間隔 普及 はりい さいぼう きょうはんしゃ 防犯 いちだい あれる 部首 とちょう おんとう 仕方がない 飽くまでも ちがい ひがい 日没 さいぼう 哀れむ ちがい ふそく かたみち すいせん えきびょう 割り箸 ねばり 擬装 ごじゅう この頃 しゃこ おりめ 飽くまでも いたずら 喜劇 こうせい 乗せる 面積 体重 きひん.",
                            SoLuongTon = 0,
                            TenSanPham = "Handmade Frozen Chicken"
                        },
                        new
                        {
                            Id = new Guid("46368202-3e68-4846-8ef3-be3cca89883b"),
                            GiaBan = 0m,
                            MoTa = "せいじょう ごじゅう 超音波 ちらかす 送る ごうけん 出かける まぎらす 奴ら 合う 羊毛 かつ きょうはんしゃ 果樹 ころす おかね 輸出 左手 こうせい 店 こうちょく かたみち はなぢ かくじっけん 電源 提案する しょうりゃく 掛ける はんそう 防犯 話 はなはだ のき 地面 じきしょうそう とちょう きょうしつ あびる すいせん むぜい もうす 人性 ちきゅう 親切 せいじょう 自立 さいぼう やさしい 学者 境.",
                            SoLuongTon = 0,
                            TenSanPham = "Unbranded Concrete Salad"
                        },
                        new
                        {
                            Id = new Guid("43cc6937-39b5-4c4c-ae0a-8acaf3b4d1db"),
                            GiaBan = 0m,
                            MoTa = "ぶん 品詞 自宅 老齢 禍根 親切 終点 ぶん せっぷく 仕方がない 大仏 たて こくふくする がいよう 狂う 陳列室 どうけつ めいし ほにゅうびん 救急車 鍋 明治 シアトルし いちだい 汚す 先週 無糖 独裁 ちきゅう 不可欠 大尉 防犯 かんそく さいぼう じっかん とうき 縛る はんそう じぎする こうぞく ぼくし 伝統 つうやく ふさい 投資 おきゃくさん せんたくする 黙る しえんする はなはだ.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Metal Pizza"
                        },
                        new
                        {
                            Id = new Guid("2cf2bdd8-b35f-4dc0-8d68-a8a552ce0304"),
                            GiaBan = 0m,
                            MoTa = "割り箸 大尉 春休み あおい ごじゅう ことばつき あつかい 牛乳 ころす 九日 屈む あう りゃくず 下着 面 揺さぶる 殻 施行 ちゅうもんする 狂う しゅしょう そんざい ようい むぼう 十台 しょうりゃく 丼 ひかくする 堀川 ほにゅうびん とりあえず 以下 しえんする 徳川 天井 しばふ 終点 旧姓 塾生 擬装 屈む じっかん 天井 かたみち しきもう しょうじょう むぼう かっこう 貫く きいろ.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Soft Chicken"
                        },
                        new
                        {
                            Id = new Guid("47995fea-c252-4932-840d-a6ec53609934"),
                            GiaBan = 0m,
                            MoTa = "ゆるむ とうさん ねんじゅう 悲しみ しゅしょう めいがら 堀川 〜亭 遺失 きいろ 独裁 かっこう きょうかい ほうげん 窓 陳列室 閉める 悲しみ はんだんする いう 遺失 かくじっけん 原油 浸す 評価 せんりゅう 薬 かっこう 遺失 ずいぶん 金縛り 店 たいやく 話 安泰 十台 こくふくする ぼくし おんとう とくに 評価 警官 かい 暴力 丼 じぎする いつ頃 浅い 米兵 しあとるし.",
                            SoLuongTon = 0,
                            TenSanPham = "Sleek Metal Mouse"
                        },
                        new
                        {
                            Id = new Guid("bb602b54-637e-41b3-a07f-5da683e603be"),
                            GiaBan = 0m,
                            MoTa = "復旧 金 指紋 活用 かん ひんかく だくりゅう 閉める つなひき うんがいい しばふ へいがい きいろ しょうじょう 貫く 果てる 果てる 渦巻き 底 いちだい たれる 色盲 長唄 大丈夫 雇用 壮年 奇襲 むらさきいろ 靖国神社 量 休日 斬殺 けいむしょ 部首 魅力 新婚旅行 ほうげん つうやく 弱虫 せんたくする 誓い 浅い はりい 全日本 電源 始まる 委員 けいかん 伐採 間隔.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Granite Gloves"
                        },
                        new
                        {
                            Id = new Guid("a0ce9c34-e191-4f88-b282-b2bd7d9fb75e"),
                            GiaBan = 0m,
                            MoTa = "入江 既に ずいぶん 重い 漂う 総括 無駄 けいかん じょうじゅん 希望する はっぽう やさい 喜劇 約する たて 問題 おりめ ぞくご 人口 手作り 殺人者 じょうき とりあえず さくにゅう 推奨 すんか 検査 杏 堀川 こわす じょうき 恨み げいひんかん ひんかく 老齢 いう ほうせき たいさ うんがいい かぜ しょくん はなじ 血液 もうす 伐採 しゃっか この頃 徳川 芸者 迷子.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Granite Cheese"
                        },
                        new
                        {
                            Id = new Guid("f8f8f00a-94bf-4166-a613-df69b78519c7"),
                            GiaBan = 0m,
                            MoTa = "宜しく なおさら とうさん 同僚 全日本 暴力 ちらかす きもち せんじょうざい 果樹 ぶき 無糖 あびる そんざい きょうはんしゃ 浅い いちだい 問題 ぞくご かっこう きょうふ あらあらしい とくに きひん 人性 唄う ちゅうもんする 休日 退く 天井 俵 量 しずむ ほんらい 無駄 迷路 さいほう はなじ 味噌 むぜい 終点 宜しく いちだい とくに 見当たる あしくび 殻 牛乳 ねんじゅう 秘める.",
                            SoLuongTon = 0,
                            TenSanPham = "Generic Plastic Computer"
                        },
                        new
                        {
                            Id = new Guid("fbc12cad-380f-4b69-9496-488430854fce"),
                            GiaBan = 0m,
                            MoTa = "あう ぶそう 九日 みつ しょうりゃく ないしょばなし こうせい 指紋 きゅうりょう 休日 むく よぼう この頃 たいさ めいがら 施行 歯を磨く 騎兵 閉じる せんりゅう 色盲 洋服 委員 抑制 きょうはんしゃ まつり 自宅 はちまき ひんきゃく あらそう りょうど けいけんしゃ 色盲 いつ頃 おりめ あつかい 好き げいひんかん しょうがっこう じぶん 底 汚す 済ます かっこう 迷子 間隔 おかね 金 一文字 みなと.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Granite Chicken"
                        },
                        new
                        {
                            Id = new Guid("e872b304-ebc3-4494-a5a9-2859625ac9d1"),
                            GiaBan = 0m,
                            MoTa = "逆 悲しみ つうやく けしき 大尉 ぶっきょう 液体 勇気 希望する 太る せいじょう 割り箸 あっとうする こうせい 重い 金縛り 歯を磨く せっぷく ちがい じじょでん 華やか 鈍器 壊す 血液 差し上げる 十台 隆起 平安 ごふく ひきざん 魅力 窓 難しい 金星 擬装 やさしい 大仏 暇 フランス語 じぶん 大尉 明治 体重 同僚 都合 けいかん 徳川 牛乳 超〜 問題.",
                            SoLuongTon = 0,
                            TenSanPham = "Licensed Fresh Bike"
                        },
                        new
                        {
                            Id = new Guid("01331617-e6e4-4e34-9222-6966c0bd1c05"),
                            GiaBan = 0m,
                            MoTa = "きょうしつ 伝統 全日本 碁 廃墟 しきもう 春休み かわかす フランス人 右利き けしき つぎつぎ いつ頃 奴ら どうけつ みなもと 気持ちいい うえる ししょく 電源 しずむ きげんご けしき 堀川 九日 いう こくふくする かんじる ぶそう きょだい やさしい 下さい 伐採 一文字 はっぽう すいせん こはん 揺さぶる フランス語 馬鹿馬鹿しい シアトルし かいぞく はなぢ かぶしきしじょう ぞくご じじょでん 量 交錯 ちかく ゆるむ.",
                            SoLuongTon = 0,
                            TenSanPham = "Handmade Soft Fish"
                        },
                        new
                        {
                            Id = new Guid("5b6ccb53-c581-4a0a-a707-3da54af99e33"),
                            GiaBan = 0m,
                            MoTa = "陳列室 味噌 ぼきん うんがいい かん 鍋 とうさん ひんきゃく 底 あつかい 華やか じぎする 長唄 めいし 活用 大尉 あしくび おととい じぎする 母 まぎらす ちきゅう にんい あらそう もはん 浸す かんどうする しょうじょう たつ 悲しみ ぶっきょう 陳列室 しゃこ 検査 掛ける ちかく 察知 ひかくする 色々 かぜ もはん はっぽう 同僚 ちあん 迷路 桜色 じっかん 窒息 浮世絵 まもる.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Fresh Shoes"
                        },
                        new
                        {
                            Id = new Guid("d8737759-92c9-4966-a13d-343b941d8a00"),
                            GiaBan = 0m,
                            MoTa = "壊す 配慮 九日 やしなう 黙る こうちょく 間隔 きゅうりょう かたみち かぜ 揺さぶる もうす 魔術 しゅしょう そあく 鍋 仕方がない 核実験 俵 見当たる 差し上げる くつじょく じぶん はなぢ けいけんしゃ 太る よわよわしい 泳ぐ しきもう 壊す まつり 話 窒息 核実験 普及 じょうじゅん うんがいい 歯を磨く こいぬ ちえん うえる 隆起 陳列室 みつ あらそう れつあく 運ぶ ねんじゅう やさしい なんべい.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Wooden Keyboard"
                        },
                        new
                        {
                            Id = new Guid("e6301a2c-2276-4acc-a8ae-4b4138acd213"),
                            GiaBan = 0m,
                            MoTa = "防犯 きょうどう ひきざん けいむしょ こうせい しばふ にる 窓 きんく 鍋 しきもう 察知 碁 機嫌 さくにゅう ふん 形 こわす 普及 普及 渦巻き 遮断 ふん じゅうらい 擬装 遮断 みなもと 誓い どろ 米兵 せんじょうざい きょうふ 大丈夫 きょうき ちゅうもんする こくふくする こくふくする もうす 靖国神社 揺さぶる ふさい 奉仕 核実験 普及 さいほう おきゃくさん きいろ そだてる 老齢 差し上げる.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Metal Hat"
                        },
                        new
                        {
                            Id = new Guid("d7d2a933-f74d-4415-868c-9cb78c63bb40"),
                            GiaBan = 0m,
                            MoTa = "せんじょうざい 俵 あらす 凝固 あう たいりく ざぜん あらあらしい はんだんする 浅い 全日本 味噌 たつ 入江 ごうけん めいがら 運ぶ じぶん 日欧 没落 せいじょう ふかさ けいじばん 明治 学院 ちらかす せんたくする じょうき ひきさく しゃくや ずいぶん 汚す かぜ 鈍器 かんしん けいけんしゃ 特殊 もうす 壮年 しょうじょう 学者 おんとう 待合 馬鹿馬鹿しい きょうしつ やさい 軒 うえる かいたく きょうどう.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Fresh Computer"
                        },
                        new
                        {
                            Id = new Guid("74a6ca73-d184-453f-961b-a7b42223bb62"),
                            GiaBan = 0m,
                            MoTa = "こはん ようい 華やか 廉価 きげんご いちだい 巡回 〜亭 誘惑 羊毛 しばふ 漂う おりめ おととい つく ひがい せっぷく 譜面 不思議 ちゅうもんする おりめ 出かける たまご はんそう 伐採 しょうかする 誤用 こいぬ ぶそう かんじる 約する 白菊 ごふく いく 雇用 ころす ざんぴん みさき そあく 殺人者 羊毛 長唄 みさき 形 先ず こうちょく 雇用 どろ たいりく おりめ.",
                            SoLuongTon = 0,
                            TenSanPham = "Tasty Steel Bike"
                        },
                        new
                        {
                            Id = new Guid("3210566f-e7ea-4ca3-9bc9-bd6d4aa9b7a6"),
                            GiaBan = 0m,
                            MoTa = "かいたく はだか 号 九日 たいりく 体重 りゃくず こはん すんか しょうがっこう ごうけん めいしょ むく 入江 ようい 味噌 血液 迷路 犠牲 しきもう 戦没 仕事 原油 もはん 急騰 秘める 交錯 狂う やさい きょうかい きょうふ 合う あくれい 人性 桜色 狂う りゅうこうご 縛る 自宅 はだか しえんする きいろ しょうじょう 退く 遮断 恨み 境 ほうげん よくげつ 金.",
                            SoLuongTon = 0,
                            TenSanPham = "Handcrafted Soft Fish"
                        },
                        new
                        {
                            Id = new Guid("bfee866c-e60e-4d91-bccf-b3c7ec9bd50b"),
                            GiaBan = 0m,
                            MoTa = "あれる 薬 こうちょく かんぜん めいし むこう 入江 丼 電話 しきもう つなひき さいほう 長唄 以下 かんしん じぎする 閉じる せいぞう まつり 秘める 一文字 店舗 遮断 雇用 切迫 以下 げんめつ おどろく ほうしゅう たいこうする 待合 ふかさ 床 天井 大丈夫 〜系 つばさ たいこうする 縛る 人口 施行 雑音 おととい 明治 ざんぴん せいじょう せっぷく 鍋 狂う きょうどう.",
                            SoLuongTon = 0,
                            TenSanPham = "Handmade Concrete Hat"
                        },
                        new
                        {
                            Id = new Guid("0e220c8a-d980-4d28-b199-15da6a652797"),
                            GiaBan = 0m,
                            MoTa = "ひきさく くつじょく せいじょう 金星 復旧 ぼうず 量 先週 伝統 そだてる なんべい 奇襲 騎兵 たれる よぼう 遮断 雑音 きひん 旧姓 じっかん しずむ やさしい せんりゅう 誤用 ひきざん とりあえず 委員 あびる どろ 十台 評価 壊す きょうき 左手 哀れむ にんい 歯を磨く 間隔 きょだい 巡回 江戸 旧姓 きゅうりょう 人性 九日 勇気 休日 汚す かん こはん.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Soft Soap"
                        },
                        new
                        {
                            Id = new Guid("0c1e4f9b-fafe-49a2-99e2-5b0377054301"),
                            GiaBan = 0m,
                            MoTa = "しゅしょう かんそく 廃墟 壊す ちかく さきまわり ちかく 店舗 誓い 靖国神社 しょくん 検査 ようい まつ 床 書き方 〜系 近視 減俸 全日本 ほうしゅう 超〜 ぞくご 電源 あらす 不健康 江戸 れつあく じじょでん はなはだ あしくび 閉じる 以下 丼 はんだんする やさい そあく 徳川 こはん しょうりゃく しえんする 擬装 かくじっけん 同僚 しゃこ みなと 魔術 あらあらしい 魔術 急騰.",
                            SoLuongTon = 0,
                            TenSanPham = "Fantastic Frozen Ball"
                        },
                        new
                        {
                            Id = new Guid("2c0f2ffc-b8e9-4d7a-8337-6b404c78ccfe"),
                            GiaBan = 0m,
                            MoTa = "寮生 せいかん けいむしょ なおさら 無糖 ぶそう むぜい 色盲 おきゃくさん げんめつ ハチのす 黒板 もはん たまご さくにゅう 始まる 学院 弥生 りゃくず 済ます いじん 近視 ざんぴん 希望する がんばる 喜劇 誓い 半額 漂う しょうゆ 恨み 下着 あらそう 戦没 杏 逆 えきびょう ひかくする こわす 封筒 ちょさくけん れつあく ごふく ひがい 提案する 学者 たれる 金縛り 始まる 推奨.",
                            SoLuongTon = 0,
                            TenSanPham = "Gorgeous Wooden Gloves"
                        },
                        new
                        {
                            Id = new Guid("29cb9ac0-c4d0-4fd8-801e-eec474f0fa19"),
                            GiaBan = 0m,
                            MoTa = "よわよわしい 気持ちいい 十台 けいむしょ 原油 陳列室 味噌 誓い 品詞 擬装 ちらかす けいじばん はちまき 俵 まつり 誓い 病床 じょうじゅん かいぞく ぶん ぶき 提案する じゅうらい ないしょばなし 〜亭 鈍器 こくみん 誓い つうやく つばさ 零す しょうがっこう ちきゅう じっかん 壊す 殻 きひん れつあく 靖国神社 誘惑 掛ける すいせん かいぞく 傑作 〜亭 礎 こはん 飽くまでも 都合 抑制.",
                            SoLuongTon = 0,
                            TenSanPham = "Sleek Plastic Keyboard"
                        },
                        new
                        {
                            Id = new Guid("77814752-d512-4aa7-a516-83cddc5c3b70"),
                            GiaBan = 0m,
                            MoTa = "出版 きゅうりょう 学院 色盲 つなひき 投資 防犯 壊す 零す しあとるし 魅力 碁 不思議 こうせい かんそく 出版 送る 終点 なんべい 桜色 きょうどう めいがら 味噌 廃墟 先ず よわよわしい 窒息 壮年 かい 飽くまでも 同僚 ひんかく 助手 いじん 待合 こうおつ 特殊 仕方がない もはん しゃこ むらさきいろ 浅い 仕方がない ふかさ りょうど 魔術 ぶそう しょくん まつり せんじょうざい.",
                            SoLuongTon = 0,
                            TenSanPham = "Intelligent Fresh Chicken"
                        },
                        new
                        {
                            Id = new Guid("12661273-4cae-4306-86fc-a4080327ca9e"),
                            GiaBan = 0m,
                            MoTa = "しょうゆ 割り箸 薬 仕事 報じる 報じる 陳列室 先ず 味噌 送る すいせん 底 殺人者 きょうふ 活用 右翼 きひん むぜい かんじる めいし 弱虫 人性 液体 しょうりゃく うんがいい しょくん みなと しあとるし 歯を磨く はなじ いたずら かいぞく 大尉 窓 あびる 〜系 杏 ふくへい こはん 部首 金縛り 米兵 急騰 みなと 渦巻き この頃 やさい 差し上げる 学者 かいたく.",
                            SoLuongTon = 0,
                            TenSanPham = "Ergonomic Granite Chips"
                        },
                        new
                        {
                            Id = new Guid("25b067ba-6cfe-4a05-9234-ccb5d7aa5180"),
                            GiaBan = 0m,
                            MoTa = "先ず 禍根 ちえん じきしょうそう 金星 ごふく 気持ちいい 賢明 塾生 送る おどろく ねんじゅう 逆 休日 寮生 ふかさ そあく まつり 伐採 芸者 ぼきん 碁 徳川 哀れむ 仕事 防犯 はなじ いく しょうゆ けいかん ちきゅう 見当たる しゃこ せんじょうざい そだてる おんとう はだか まぎらす けいかん 部首 指紋 泳ぐ 一文字 おかね 終点 ちきゅう 退く 軒 かたみち 礎.",
                            SoLuongTon = 0,
                            TenSanPham = "Ergonomic Soft Salad"
                        },
                        new
                        {
                            Id = new Guid("b5982e5d-48a4-4a08-9106-96a732d97eb2"),
                            GiaBan = 0m,
                            MoTa = "ねんじゅう いちだい 電話 老齢 うえる ごじゅう 暇 液体 開閉 母 血液 堀川 せんじょうざい 病床 唄う ごじゅう 軒 この頃 勇気 逆 ようい しゃこ 警官 犠牲 じゅうどう あれる たいこうする しょうりゃく やさい ひきざん 底 なおさら とくに 合う あれる じきしょうそう 底 果てる 伝統 憂い 殻 救急車 じきしょうそう ほうせき きひん さいぼう いっさくじつ 掛ける しょうがっこう めいし.",
                            SoLuongTon = 0,
                            TenSanPham = "Unbranded Plastic Chips"
                        },
                        new
                        {
                            Id = new Guid("3047918d-f5e4-4cef-bc43-02382e061971"),
                            GiaBan = 0m,
                            MoTa = "とふ 白菊 いく かおつき 運ぶ 見当たる たいこうする 気持ちいい だいどころ 委員 既に さくにゅう 鍋 はっぽう にんい 出かける たて 双 まほうつかい こくふくする 検査 うえる かぶしきしじょう 誘惑 しえんする 傑作 うえる すいせん ぐん 太る 継承 体重 抑制 斬殺 日欧 しばふ 仕方がない こうぞく ざんぴん 味噌 ひがい じょうじゅん 書き方 おりめ 自宅 せんじょうざい 差し上げる 防犯 けしき せんりゅう.",
                            SoLuongTon = 0,
                            TenSanPham = "Rustic Wooden Chicken"
                        },
                        new
                        {
                            Id = new Guid("f411948f-9a55-44a7-afcb-6973527cee7f"),
                            GiaBan = 0m,
                            MoTa = "妥協する くつじょく 核実験 つく せんじょうざい ひきさく はなぢ 境 浮世絵 廉価 交錯 だくりゅう 漠然 無駄 報じる 助手 はりい しゅしょう 運ぶ 金星 せんじょうざい たまご いく 量 都合 じぶん 無糖 はっぽう 警官 あしくび 提案する 右翼 学者 暴力 のき つなひき 雑音 妥協する 掛ける 閉める 遺失 逆 掛ける あれる きょうき 機嫌 りょうど 乗せる ずいぶん 弱虫.",
                            SoLuongTon = 0,
                            TenSanPham = "Awesome Cotton Car"
                        });
                });

            modelBuilder.Entity("DanhMucSanPham", b =>
                {
                    b.HasOne("SeedData.Models.DanhMuc", null)
                        .WithMany()
                        .HasForeignKey("DanhMucsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedData.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("SanPhamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DonHangSanPham", b =>
                {
                    b.HasOne("SeedData.Models.DonHang", null)
                        .WithMany()
                        .HasForeignKey("DonHangsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedData.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("SanPhamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeedData.Models.DonHang", b =>
                {
                    b.HasOne("SeedData.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SeedData.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
