// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedData.Context;

#nullable disable

namespace SeedData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806142801_NormalSeedData")]
    partial class NormalSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SeedData.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65197395-6baf-463b-8952-862efc23d831"),
                            MoTa = "SP1",
                            TenSanPham = "San pham 1"
                        },
                        new
                        {
                            Id = new Guid("4b23fa81-784b-4b03-be59-4285b9b2d949"),
                            MoTa = "SP2",
                            TenSanPham = "San pham 2"
                        },
                        new
                        {
                            Id = new Guid("11772746-d676-4046-8f16-d51d420afe98"),
                            MoTa = "SP3",
                            TenSanPham = "San pham 3"
                        },
                        new
                        {
                            Id = new Guid("4c73d08d-2157-4b8d-b4f9-d52528e3c8d6"),
                            MoTa = "SP4",
                            TenSanPham = "San pham 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
